/* ============================================
   STAGEPULSE – script.js (Güvenlik güçlendirmeli)
   - Network-first uyumlu
   - Proper GA Consent Mode v2
   - Public quote intake Edge Function
   - Honeypot + Turnstile + client rate-limit
   - Daha sağlam cookie / form yönetimi
   ============================================ */

const FORMSPREE_ENDPOINT = 'https://formspree.io/f/xrpzeegb';
const TURNSTILE_SITE_KEY = '0x4AAAAAAENv1kw4YHXe-Gih';
const SUPABASE_URL = 'https://mtjcqqrogjqaxkagwkti.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_yR_HlWlFbYYq22tQmiB9LA_acq6bQi6';
const PUBLIC_QUOTE_EDGE = `${SUPABASE_URL}/functions/v1/public-quote`;
let supabase = null;

function loadSupabase(){return new Promise(resolve=>{if(window.supabase&&window.supabase.createClient){supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);resolve(supabase);return}const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.async=true;script.onload=()=>{if(window.supabase&&window.supabase.createClient)supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);resolve(supabase)};script.onerror=()=>resolve(null);document.head.appendChild(script)})}
function t(key,fallbackTr,vars){const lang=localStorage.getItem('lang')||'tr';let str=(typeof translations!=='undefined'&&translations[lang]&&translations[lang][key]!==undefined)?translations[lang][key]:fallbackTr;if(vars)Object.keys(vars).forEach(k=>{str=str.replace('{'+k+'}',vars[k])});return str}
function setLanguage(lang){localStorage.setItem('lang',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.getAttribute('data-i18n');if(translations[lang]&&translations[lang][key]!==undefined)el.innerHTML=translations[lang][key]});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const key=el.getAttribute('data-i18n-placeholder');if(translations[lang]&&translations[lang][key]!==undefined)el.placeholder=translations[lang][key]});document.querySelectorAll('select option[data-i18n]').forEach(el=>{const key=el.getAttribute('data-i18n');if(translations[lang]&&translations[lang][key]!==undefined)el.textContent=translations[lang][key]});document.getElementById('btn-tr')?.classList.toggle('active',lang==='tr');document.getElementById('btn-en')?.classList.toggle('active',lang==='en')}
function initCookieConsent(){const consent=localStorage.getItem('sp_consent');if(consent==='accepted'||consent==='rejected'){updateGAConsent(consent==='accepted');return}const banner=document.createElement('div');banner.id='cookie-banner';banner.setAttribute('role','dialog');banner.setAttribute('aria-label','Çerez onayı');banner.innerHTML='<div class="cookie-inner"><p data-i18n="cookie_text">Bu site deneyimi iyileştirmek ve teklif süreçlerini yönetmek için çerezler kullanır. Devam ederek <a href="Kvkk.html" target="_blank" rel="noopener">KVKK Aydınlatma Metni</a>’ni kabul etmiş olursunuz.</p><div class="cookie-actions"><button id="cookie-accept" class="btn btn-primary" data-i18n="cookie_accept">Kabul Et</button><button id="cookie-reject" class="btn btn-outline" data-i18n="cookie_reject">Reddet</button></div></div>';document.body.appendChild(banner);document.body.classList.add('has-cookie-banner');setLanguage(localStorage.getItem('lang')||'tr');const dismissCookie=accepted=>{localStorage.setItem('sp_consent',accepted?'accepted':'rejected');banner.remove();document.body.classList.remove('has-cookie-banner');updateGAConsent(accepted)};document.getElementById('cookie-accept').addEventListener('click',()=>dismissCookie(true));document.getElementById('cookie-reject').addEventListener('click',()=>dismissCookie(false))}
function updateGAConsent(granted){if(typeof gtag==='function')gtag('consent','update',{analytics_storage:granted?'granted':'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'})}
function trackEvent(name,params={}){if(typeof gtag==='function'&&localStorage.getItem('sp_consent')==='accepted')gtag('event',name,params)}
function safeMediaUrl(path){if(!path)return '';if(/^https?:\/\//i.test(path))return path;return path.split('/').map(segment=>encodeURIComponent(segment)).join('/')}

document.addEventListener('DOMContentLoaded',()=>{
  setLanguage(localStorage.getItem('lang')||'tr');
  if(document.getElementById('stickyCta'))document.body.classList.add('has-sticky-cta');
  initCookieConsent();
  if(document.getElementById('offerForm'))loadSupabase();
  const hamburger=document.getElementById('hamburger'),navLinks=document.getElementById('navLinks'),icon=document.getElementById('hamburger-icon');
  if(hamburger&&navLinks){hamburger.addEventListener('click',()=>{const isOpen=navLinks.classList.toggle('active');hamburger.classList.toggle('open',isOpen);hamburger.setAttribute('aria-expanded',isOpen?'true':'false');icon?.classList.toggle('fa-bars',!isOpen);icon?.classList.toggle('fa-xmark',isOpen)});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('active');hamburger.classList.remove('open');hamburger.setAttribute('aria-expanded','false');icon?.classList.add('fa-bars');icon?.classList.remove('fa-xmark')}))}
  const currentPath=window.location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav-links a').forEach(a=>{const href=a.getAttribute('href');if(!href)return;const clean=href.replace('./','').replace(/^\//,'')||'index.html';if(clean===currentPath||(currentPath===''&&clean==='index.html'))a.classList.add('active')});

  const lightbox=document.getElementById('lightbox'),lbImg=document.getElementById('lightbox-img'),lbClose=document.getElementById('lightbox-close');
  const openLightbox=src=>{if(!lightbox||!lbImg)return;lbImg.src=src;lightbox.classList.add('open');document.body.style.overflow='hidden'};const closeLightbox=()=>{if(!lightbox)return;lightbox.classList.remove('open');if(lbImg)lbImg.src='';document.body.style.overflow=''};lbClose?.addEventListener('click',closeLightbox);lightbox?.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox()});
  const gallery=document.getElementById('gallery'),heroBg=document.getElementById('heroBg'),videoBox=document.getElementById('videos'),docList=document.getElementById('documentsList');
  const galleryAlts=['Sahne line array kurulumu','FOH konsol ve miks noktası','Açık alan ses sistemi','Truss ve ışık kurulumu','Monitör ve sahne düzeni','Canlı etkinlik ses operasyonu','Sahne ve PA sistemi kurulumu','FOH mühendisliği saha çalışması'];
  (async function loadMedia(){try{const res=await fetch('media.json?_='+Date.now());if(!res.ok)return;const data=await res.json();const photos=Array.isArray(data.photos)?data.photos:[];if(gallery){gallery.innerHTML='';if(!photos.length)gallery.innerHTML='<p style="color:#666;text-align:center;padding:40px 0">Henüz fotoğraf eklenmedi.</p>';else photos.forEach((src,i)=>{const img=document.createElement('img');const url=safeMediaUrl(src);img.src=url;img.loading='lazy';img.alt=galleryAlts[i%galleryAlts.length];img.addEventListener('click',()=>openLightbox(url));gallery.appendChild(img)})}if(heroBg&&photos.length){let i=0;const setBg=n=>{const url=safeMediaUrl(photos[n]);heroBg.style.backgroundImage='linear-gradient(110deg,rgba(0,0,0,.93),rgba(0,0,0,.5)), url("'+url+'")'};setBg(0);setInterval(()=>{i=(i+1)%photos.length;setBg(i)},5500)}const videos=Array.isArray(data.videos)?data.videos:[];if(videoBox){videoBox.innerHTML='';if(!videos.length){const section=videoBox.closest('section')||videoBox.closest('.section');if(section)section.style.display='none'}else videos.forEach(src=>{const v=document.createElement('video');v.src=safeMediaUrl(src);v.controls=true;v.preload='metadata';v.playsInline=true;videoBox.appendChild(v)})}const docs=Array.isArray(data.documents)?data.documents:[];if(docList){docList.innerHTML='';if(!docs.length)docList.innerHTML='<div class="doc-card"><i class="fa-solid fa-file-pdf"></i><h3 data-i18n="d_empty_title">Henüz doküman eklenmedi</h3><p data-i18n="d_empty_desc">PDF documents klasörüne yükleyin</p></div>';else docs.forEach(d=>{const rawPath=typeof d==='string'?d:(d.path||d.file||d.url||'');const rawName=typeof d==='string'?d:(d.title||d.name||rawPath||'Doküman');const displayName=String(rawName).split('/').pop().replace(/\.pdf$/i,'').replace(/[-_]+/g,' ').replace(/\bStagepulse\b/gi,'Stagepulse').trim()||'Doküman';const a=document.createElement('a');a.href=safeMediaUrl(rawPath);a.target='_blank';a.rel='noopener noreferrer';a.className='doc-card';if(!rawPath){a.removeAttribute('href');a.style.pointerEvents='none';a.style.opacity='.6'}const rawIcon=(d&&typeof d.icon==='string')?d.icon:'';const safeIcon=/^[a-zA-Z0-9-]+$/.test(rawIcon)?rawIcon:'fa-file-pdf';const iconEl=document.createElement('i');iconEl.className='fa-solid '+safeIcon;const titleEl=document.createElement('h3');titleEl.textContent=displayName;const descEl=document.createElement('p');descEl.setAttribute('data-i18n','d_view');descEl.textContent='PDF görüntüle / indir';a.append(iconEl,titleEl,descEl);docList.appendChild(a)}) ;setLanguage(localStorage.getItem('lang')||'tr')}}catch(e){console.warn('Media load error',e)}})();

  let turnstileWidgetId=null,turnstileLoadFailed=false,lastSubmitTs=0;const SUBMIT_COOLDOWN_MS=15000;
  function initTurnstile(attempt=0){const el=document.getElementById('cfTurnstile'),wrap=document.getElementById('turnstileWrap');if(!el||!TURNSTILE_SITE_KEY){if(wrap)wrap.style.display='none';return}if(typeof turnstile==='undefined'){if(attempt>=15){turnstileLoadFailed=true;return}setTimeout(()=>initTurnstile(attempt+1),400);return}try{turnstileWidgetId=turnstile.render(el,{sitekey:TURNSTILE_SITE_KEY,theme:'dark',size:'normal','error-callback':()=>{turnstileLoadFailed=true}})}catch(_){turnstileLoadFailed=true}}

  const form=document.getElementById('offerForm');
  if(form){
    initTurnstile();
    const getTodayStr=()=>{const now=new Date();return now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0')+'-'+String(now.getDate()).padStart(2,'0')};
    const eventDateEl=form.querySelector('[name="date"]')||document.getElementById('eventDate');
    if(eventDateEl){const applyMinDate=()=>{const todayStr=getTodayStr();eventDateEl.setAttribute('min',todayStr);if(eventDateEl.value&&eventDateEl.value<todayStr)eventDateEl.value=''};applyMinDate();eventDateEl.addEventListener('change',applyMinDate);eventDateEl.addEventListener('input',applyMinDate);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')applyMinDate()})}
    form.querySelectorAll('input,select,textarea').forEach(el=>{el.addEventListener('input',()=>el.classList.remove('field-error'));el.addEventListener('change',()=>el.classList.remove('field-error'))});
    form.addEventListener('submit',async function(e){e.preventDefault();if(form.dataset.submitting==='1')return;const now=Date.now();if(now-lastSubmitTs<SUBMIT_COOLDOWN_MS){const wait=Math.ceil((SUBMIT_COOLDOWN_MS-(now-lastSubmitTs))/1000);showFormError(t('form_rate_limit','Lütfen '+wait+' saniye bekleyip tekrar deneyin.',{seconds:wait}));return}
      const nameEl=this.querySelector('[name="name"]')||document.getElementById('name'),companyEl=this.querySelector('[name="company"]')||document.getElementById('company'),emailEl=this.querySelector('[name="email"]')||document.getElementById('email'),eventTypeEl=this.querySelector('[name="event_type"]')||document.getElementById('eventType'),phoneEl=this.querySelector('[name="phone"]')||document.getElementById('phone'),typeEl=this.querySelector('[name="type"]')||document.getElementById('type'),locationEl=this.querySelector('[name="location"]')||document.getElementById('location'),peopleEl=this.querySelector('[name="people"]')||document.getElementById('people'),dateEl=this.querySelector('[name="date"]')||document.getElementById('eventDate'),messageEl=this.querySelector('[name="message"]')||document.getElementById('message'),kvkkEl=this.querySelector('[name="kvkk"]')||document.getElementById('kvkk'),hpEl=this.querySelector('[name="website"]');
      if(hpEl&&hpEl.value.trim()!=='')return;
      let turnstileToken='';if(TURNSTILE_SITE_KEY){if(turnstileLoadFailed){showFormError(t('form_err_turnstile_unavailable','Güvenlik doğrulaması yüklenemedi. Lütfen sayfayı yenileyip tekrar deneyin veya WhatsApp üzerinden ulaşın.'));return}if(typeof turnstile!=='undefined'&&turnstileWidgetId!==null){try{turnstileToken=turnstile.getResponse(turnstileWidgetId)||''}catch(_){ }const tw=document.getElementById('turnstileWrap');const widgetVisible=tw&&tw.offsetParent!==null&&tw.style.display!=='none';if(widgetVisible&&!turnstileToken){showFormError(t('form_err_turnstile','Lütfen güvenlik doğrulamasını tamamlayın.'));return}}}
      const name=nameEl?.value.trim()||'',company=companyEl?.value.trim()||'',email=emailEl?.value.trim()||'',eventType=eventTypeEl?.value||'',phone=phoneEl?.value.trim()||'',type=typeEl?.value||'',location=locationEl?.value.trim()||'',people=peopleEl?.value.trim()||'',date=dateEl?.value||'',message=messageEl?.value.trim()||'',kvkk=!!kvkkEl?.checked;
      function showFormError(msg,focusEl){form.dataset.submitting='0';let err=document.getElementById('formError');if(!err){err=document.createElement('div');err.id='formError';err.setAttribute('role','alert');err.style.cssText='background:#ff3333;color:#fff;padding:12px 16px;border-radius:8px;margin:12px 0;font-size:14px;text-align:center;'}const btn=form.querySelector('button[type="submit"]');if(btn?.parentNode)btn.parentNode.insertBefore(err,btn);else if(!err.parentNode)form.appendChild(err);err.textContent=msg;err.style.display='block';if(focusEl){focusEl.classList.add('field-error');const section=focusEl.closest('.sp-offer-section');if(section){form.querySelectorAll('.sp-offer-section').forEach(x=>x.classList.remove('is-open'));section.classList.add('is-open')}const target=focusEl.closest('.form-group')||focusEl.closest('label.kvkk-label')||focusEl;setTimeout(()=>{try{target.scrollIntoView({behavior:'smooth',block:'center'})}catch(_){}try{focusEl.focus({preventScroll:true})}catch(__){}},80)}else{try{err.scrollIntoView({behavior:'smooth',block:'center'})}catch(_){}}setTimeout(()=>{err.style.display='none'},8000)}
      if(!name)return showFormError(t('form_err_name','Lütfen Ad Soyad / Firma alanını doldurun.'),nameEl);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return showFormError(t('form_err_email','Lütfen geçerli bir e-posta adresi girin.'),emailEl);if(!phone)return showFormError(t('form_err_phone','Lütfen Telefon numaranızı girin.'),phoneEl);if(!eventType)return showFormError(t('form_err_event_type','Lütfen etkinlik türünü seçin.'),eventTypeEl);if(!type)return showFormError(t('form_err_type','Lütfen Hizmet Türü / Paket seçin.'),typeEl);if(!location)return showFormError(t('form_err_location','Lütfen Lokasyon / Şehir alanını doldurun.'),locationEl);if(!people||isNaN(Number(people))||Number(people)<1||Number(people)>100000)return showFormError(t('form_err_people','Lütfen geçerli bir Tahmini Katılımcı Sayısı girin (1 - 100.000 arası).'),peopleEl);if(!/^[0-9+\s()\-]{7,20}$/.test(phone))return showFormError(t('form_err_phone_invalid','Lütfen geçerli bir Telefon numarası girin.'),phoneEl);if(!date)return showFormError(t('form_err_date','Lütfen Etkinlik Tarihini seçin.'),dateEl);const todayStr=getTodayStr();if(dateEl)dateEl.setAttribute('min',todayStr);if(date<todayStr){if(dateEl)dateEl.value='';return showFormError(t('form_err_date_past','Etkinlik Tarihi geçmiş bir tarih olamaz. Lütfen bugün veya sonrası için bir tarih seçin.'),dateEl)}if(!message)return showFormError(t('form_err_message','Lütfen mesaj / etkinlik detaylarını yazın.'),messageEl);if(!kvkk)return showFormError(t('form_err_kvkk','Devam etmek için KVKK onay kutusunu işaretlemeniz gerekmektedir.'),kvkkEl);
      form.dataset.submitting='1';lastSubmitTs=Date.now();const submitBtn=form.querySelector('button[type="submit"]');if(submitBtn){submitBtn.disabled=true;submitBtn.style.opacity='0.7'}const waWindow=(()=>{try{return window.open('about:blank','_blank','noopener,noreferrer')}catch(_){return null}})();
      const body={name,company,email,event_type:eventType,type,location,people:Number(people),event_date:date,message,kvkk,website:hpEl?.value||'',turnstile_token:turnstileToken};let supabaseSaved=false;
      try{const r=await fetch(PUBLIC_QUOTE_EDGE,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_ANON_KEY},body:JSON.stringify(body)});const payload=await r.json().catch(()=>({}));if(!r.ok)throw new Error(payload.error||'Talebiniz kaydedilemedi.');supabaseSaved=payload.ok===true}catch(err){console.error('Public quote error:',err);form.dataset.submitting='0';const errBox=document.getElementById('formError')||document.createElement('div');errBox.id='formError';errBox.setAttribute('role','alert');errBox.textContent=t('form_err_submit','Talebiniz kaydedilemedi. Lütfen birkaç dakika sonra tekrar deneyin veya WhatsApp üzerinden ulaşın.');if(!errBox.parentNode)form.insertBefore(errBox,form.querySelector('button[type=submit]'));if(submitBtn){submitBtn.disabled=false;submitBtn.style.opacity='1'}try{waWindow?.close()}catch(_){ }return}
      let emailSent=false;if(FORMSPREE_ENDPOINT){try{const formData=new FormData(form);if(turnstileToken)formData.append('cf-turnstile-response',turnstileToken);formData.delete('website');const mailResponse=await fetch(FORMSPREE_ENDPOINT,{method:'POST',body:formData,headers:{Accept:'application/json'}});emailSent=mailResponse.ok}catch(err){console.warn('Quote email notification failed:',err)}}
      if(TURNSTILE_SITE_KEY&&typeof turnstile!=='undefined'&&turnstileWidgetId!==null){try{turnstile.reset(turnstileWidgetId)}catch(_){} }
      const waText='Yeni Teklif Talebi%0A%0A'+'Ad: '+encodeURIComponent(name)+'%0ATelefon: '+encodeURIComponent(phone)+'%0AHizmet: '+encodeURIComponent(type)+'%0ALokasyon: '+encodeURIComponent(location||'-')+'%0AKişi: '+encodeURIComponent(people||'-')+'%0ATarih: '+encodeURIComponent(date||'-')+'%0AMesaj: '+encodeURIComponent(message);const waUrl='https://wa.me/905320683012?text='+waText;let waOpened=false;if(waWindow&&!waWindow.closed){try{waWindow.location.href=waUrl;waOpened=true}catch(_){}}if(!waOpened){try{const a=document.createElement('a');a.href=waUrl;a.target='_blank';a.rel='noopener noreferrer';a.style.display='none';document.body.appendChild(a);a.click();a.remove();waOpened=true}catch(_){} }
      let msg=document.getElementById('formSuccess');if(!msg){msg=document.createElement('div');msg.id='formSuccess';msg.className='form-success';form.appendChild(msg)}msg.innerHTML=`<strong>${t('form_success_title','Talebiniz başarıyla alındı.')}</strong><span>${t('form_success_saved','Bilgileriniz Stagepulse sistemine kaydedildi.')}</span><span>${emailSent?t('form_success_email_ok','Bildirim e-postası da oluşturuldu.'):t('form_success_email_fail','Bildirim e-postası gönderilemedi; talebiniz sistemde kayıtlı.')}</span><a class="form-success-wa" href="${waUrl}" target="_blank" rel="noopener"><i class="fa-brands fa-whatsapp"></i> ${t('form_success_wa_btn',"WhatsApp'tan devam et")}</a>`;msg.classList.add('show');trackEvent('generate_lead',{event_category:'form',event_label:type});form.reset();setTimeout(()=>{if(submitBtn){submitBtn.disabled=false;submitBtn.style.opacity='1'}form.dataset.submitting='0'},2500);
    })
  }
  document.querySelectorAll('a[href*="wa.me"]').forEach(a=>a.addEventListener('click',()=>trackEvent('contact',{method:'whatsapp'})));
  document.querySelectorAll('a[href^="tel:"]').forEach(a=>a.addEventListener('click',()=>trackEvent('contact',{method:'phone'})));
});