/* Stagepulse Service Worker v15 — public navigation compatibility + customer AI injection. */
const CACHE_VERSION='stagepulse-v15';
const STATIC_CACHE=`static-${CACHE_VERSION}`;
const MEDIA_CACHE=`media-${CACHE_VERSION}`;
const PRECACHE_ASSETS=['/favicon.svg','/manifest.webmanifest','/i18n.js','/site-ai.js','/site-ai.css','/ai-knowledge.json'];
const NAV_CSS=`<style id="stagepulse-nav-fix">.hamburger{position:relative;display:inline-flex;align-items:center;justify-content:center}.hamburger #hamburger-icon{display:none!important}.hamburger::before{content:"";position:absolute;width:24px;height:2px;border-radius:2px;background:#fff;transform:translateY(-7px);box-shadow:0 7px 0 #fff,0 14px 0 #fff}.hamburger:hover::before{background:#ffb000;box-shadow:0 7px 0 #ffb000,0 14px 0 #ffb000}.lang-switch{display:flex;align-items:center;gap:8px}.lang-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px}.flag-icon{display:block;flex:0 0 auto}</style>`;
const AI_CSS='<link rel="stylesheet" href="/site-ai.css">';
const AI_JS='<script src="/site-ai.js" defer></script>';
async function decorateHtml(response){const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;try{const html=await response.text();let decorated=html;if(!html.includes('id="stagepulse-nav-fix"'))decorated=decorated.replace(/<\/head>/i,NAV_CSS+'</head>');if(!html.includes('/site-ai.js')){decorated=decorated.replace(/<\/head>/i,AI_CSS+'</head>');decorated=decorated.replace(/<\/body>/i,AI_JS+'</body>')}const headers=new Headers(response.headers);headers.set('content-type','text/html; charset=UTF-8');return new Response(decorated,{status:response.status,statusText:response.statusText,headers});}catch(_){return response;}}
self.addEventListener('install',event=>event.waitUntil(caches.open(STATIC_CACHE).then(c=>c.addAll(PRECACHE_ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==STATIC_CACHE&&k!==MEDIA_CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('push',event=>{let payload={};try{payload=event.data?event.data.json():{}}catch(_){payload={notification:{body:event.data?event.data.text():''}}}const n=payload.notification||{},d=payload.data||{},title=n.title||d.title||'Stagepulse',body=n.body||d.body||'',url=d.url||n.click_action||'/';event.waitUntil(self.registration.showNotification(title,{body,icon:n.icon||'/icon-192.png',badge:n.badge||'/favicon-32.png',tag:d.tag||`stagepulse-${d.notification_id||title}`,renotify:false,data:{url}}))});
self.addEventListener('notificationclick',event=>{event.notification.close();const target=event.notification?.data?.url||'/';event.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(clients=>{const existing=clients.find(c=>'focus'in c);if(existing){if('navigate'in existing&&existing.url!==new URL(target,self.location.origin).href)return existing.navigate(new URL(target,self.location.origin).href).then(()=>existing.focus());return existing.focus()}return self.clients.openWindow(new URL(target,self.location.origin).href)}))});
self.addEventListener('fetch',event=>{const {request}=event,url=new URL(request.url);if(url.origin!==self.location.origin)return;const isAuthenticatedPath=url.pathname==='/admin'||url.pathname.startsWith('/admin/')||url.pathname==='/portal'||url.pathname.startsWith('/portal/');if(isAuthenticatedPath){event.respondWith(fetch(request,{cache:'no-store'}));return}const networkFirst=request.destination==='document'||url.pathname.endsWith('.html')||url.pathname.endsWith('.css')||url.pathname.endsWith('script.js')||url.pathname.endsWith('i18n.js')||url.pathname.endsWith('media.json')||url.pathname.endsWith('app-update.json');if(networkFirst){event.respondWith(fetch(request).then(response=>{if(response&&response.status===200&&request.method==='GET'){caches.open(STATIC_CACHE).then(c=>c.put(request,response.clone()));return request.destination==='document'?decorateHtml(response):response}return response}).catch(()=>caches.match(request).then(c=>c||caches.match('/index.html')||caches.match('/'))));return}event.respondWith(caches.match(request).then(cached=>cached||fetch(request).then(response=>{if(response&&response.status===200&&request.method==='GET'){const clone=response.clone(),targetCache=request.destination==='video'||url.pathname.match(/\.(mp4|webm|mov|m4v)$/i)?MEDIA_CACHE:STATIC_CACHE;caches.open(targetCache).then(c=>c.put(request,clone))}return response}).catch(()=>request.destination==='image'?new Response('',{status:404}):caches.match('/index.html'))))});
