(function () {
  'use strict';
  const msgs=document.getElementById('msgs'),form=document.getElementById('form'),input=document.getElementById('input'),skillsPanel=document.getElementById('skillsPanel'),modeBadge=document.getElementById('modeBadge');
  const base=()=>String(window.STAGEPULSE_RUNTIME?.supabaseUrl||'').replace(/\/$/,'');
  const setOnline=()=>{modeBadge.textContent=navigator.onLine?'ONLINE · canlı':'OFFLINE';modeBadge.className='badge '+(navigator.onLine?'online':'offline')};setOnline();window.addEventListener('online',setOnline);window.addEventListener('offline',setOnline);
  const safe=t=>String(t??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n/g,'<br>');
  function addBubble(role,text,actions=[]){const d=document.createElement('div');d.className='bubble '+role;d.innerHTML=safe(text);if(actions.length){const bar=document.createElement('div');bar.className='actions';actions.forEach(a=>{if(a.type==='wa'||a.type==='link'){const x=document.createElement('a');x.href=a.href;x.target='_blank';x.rel='noopener';x.className=a.type==='wa'?'btn-wa':'btn-link';x.textContent=a.label;bar.appendChild(x)}else if(a.type==='copy'){const x=document.createElement('button');x.type='button';x.className='btn-copy';x.textContent=a.label;x.onclick=()=>navigator.clipboard?.writeText(a.payload||'').catch(()=>{});bar.appendChild(x)}});d.appendChild(bar)}msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight}
  async function getAccessToken(){const c=window.__stagepulseAdminClient||window.sb||window.supabaseClient;if(!c?.auth)throw Error('Yönetim bağlantısı hazır değil.');const r=await c.auth.getSession();if(r.error)throw r.error;const t=r.data?.session?.access_token;if(!t)throw Error('Oturum gerekli.');return t}
  async function canonical(message,history=[]){const t=await getAccessToken(),url=base()+'/functions/v1/patron-ai';const r=await fetch(url,{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({message,history:history.slice(-12)})});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||('HTTP '+r.status));return j}
  const loadHist=()=>{try{return JSON.parse(sessionStorage.getItem(window.SPAdminAgent.HIST_KEY)||'[]')}catch(_){return[]}};
  const saveHist=h=>{try{sessionStorage.setItem(window.SPAdminAgent.HIST_KEY,JSON.stringify(h.slice(-50)))}catch(_){}};
  const hist=loadHist();if(hist.length)hist.forEach(h=>addBubble(h.role==='bot'?'bot':h.role,h.text,h.actions||[]));else addBubble('bot','**Admin Jarvis Pro** hazır. Canlı AI ve şirket verileri canonical Patron JARVIS endpointinden çalışır.');
  function renderSkills(){skillsPanel.innerHTML='';(window.SP_ADMIN_KB?.skills||[]).forEach(s=>{const b=document.createElement('button');b.type='button';b.className='skill';b.textContent=s.label;b.onclick=()=>{input.value=s.sample;form.requestSubmit()};skillsPanel.appendChild(b)})}renderSkills();
  document.getElementById('btnSkills')?.addEventListener('click',()=>skillsPanel.classList.toggle('hidden'));document.getElementById('btnJobs')?.addEventListener('click',()=>{input.value='işler';form.requestSubmit()});document.getElementById('btnClear')?.addEventListener('click',()=>{sessionStorage.removeItem(window.SPAdminAgent.HIST_KEY);msgs.innerHTML='';addBubble('bot','Sohbet temizlendi.')});
  async function send(q){try{const j=await canonical(q,hist),txt=(j.reply||'Yanıt alınamadı.')+(j.provider?'\nSağlayıcı: '+j.provider:'')+(j.tool?.name?'\nTool: '+j.tool.name:'');addBubble('bot',txt);hist.push({role:'bot',text:txt});saveHist(hist)}catch(e){addBubble('bot','JARVIS bağlantı hatası: '+(e?.message||'Bilinmeyen hata'))}}
  form.addEventListener('submit',async e=>{e.preventDefault();const q=input.value.trim();if(!q)return;input.value='';addBubble('user',q);hist.push({role:'user',text:q});saveHist(hist);const local=window.SPAdminAgent.run(q);if(local.text==='LIVE_SUMMARY_REQUEST'){await send('Teklifler, işler, müşteriler, ekipman ve okunmamış bildirimlerin canlı yönetim özetini ver.');return}const localOnly=/^(yardım|help|komut|beceri|not\b|notlar|kayıtlı not|işler$|fiyat not|pricing|fiyatlandırma|bölge|region|etkinlik checklist|checklist etkinlik|foh checklist|checklist foh|ışık checklist|checklist ışık|süreç|sop|paket|wa\b|whatsapp|mesaj|taslak|takip|teyit|kurulum mesaj|brifing|brief|saha\b|gün planı|gun plani|day plan)/i.test(q);if(localOnly){addBubble('bot',local.text,local.actions||[]);hist.push({role:'bot',text:local.text,actions:local.actions||[]});saveHist(hist);return}await send(q)})
})();
