import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { PDFDocument, rgb } from "npm:pdf-lib@1.17.1";
import fontkit from "npm:@pdf-lib/fontkit@1.1.1";

const cors={"Access-Control-Allow-Origin":"https://stagepulse.com.tr","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Cache-Control":"no-store"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const money=(v:unknown)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(Number(v)||0);
const wrap=(text:string,font:any,size:number,max:number)=>{const words=text.split(/\s+/);const lines:string[]=[];let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(test,size)<=max)line=test;else{if(line)lines.push(line);line=word;}}if(line)lines.push(line);return lines;};

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(req.method!=="POST")return json({error:"Method Not Allowed"},405);try{
 const h=req.headers.get("authorization")||"";if(!h.toLowerCase().startsWith("bearer "))return json({error:"Oturum gerekli."},401);
 const url=Deno.env.get("SUPABASE_URL")!,sk=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,ak=Deno.env.get("SUPABASE_ANON_KEY")!;
 const uc=createClient(url,ak,{global:{headers:{Authorization:h}},auth:{persistSession:false}});const {data:ud,error:ue}=await uc.auth.getUser(h.slice(7).trim());if(ue||!ud.user)return json({error:"Oturum gerekli."},401);
 const {data:m,error:me}=await uc.from("org_memberships").select("user_id,active,role:role_id(code,is_admin_role)").eq("user_id",ud.user.id).eq("active",true).maybeSingle();if(me||!m)return json({error:"Yönetici oturumu gerekli."},403);
 const role=Array.isArray((m as any).role)?(m as any).role[0]:(m as any).role;const {data:g,error:ge}=await uc.from("admin_capability_grants").select("capability_key").eq("user_id",ud.user.id).eq("enabled",true);if(ge)return json({error:"Yetki kontrolü başarısız."},403);const caps=new Set((g||[]).map((x:any)=>x.capability_key).filter(Boolean));if(role?.code!=="owner"&&!caps.has("offers.pdf"))return json({error:"Teklif PDF yetkisi gerekli."},403);
 const b=await req.json().catch(()=>({})),oid=String(b?.offer_id||"");if(!oid)return json({error:"offer_id gerekli."},400);
 const db=createClient(url,sk,{auth:{persistSession:false}});const {data:o,error:oe}=await db.from("teklifler").select("*").eq("id",oid).single();if(oe||!o)return json({error:"Teklif bulunamadı."},404);
 const {data:rawItems}=await db.from("offer_items").select("description,quantity,unit_price,total,notes,equipment_id").eq("offer_id",oid).order("created_at");const {data:rawPhotos}=await db.from("offer_attachments").select("storage_path,file_name,mime_type,customer_visible,sort_order").eq("offer_id",oid).eq("customer_visible",true).order("sort_order").order("created_at");const items=Array.isArray(rawItems)?rawItems:[];const photos=Array.isArray(rawPhotos)?rawPhotos:[];
 const [fontBytes,boldBytes]=await Promise.all([fetch("https://raw.githubusercontent.com/notofonts/noto-fonts/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf",{signal:AbortSignal.timeout(10_000)}).then(r=>{if(!r.ok)throw new Error("FONT_FETCH_FAILED");return r.arrayBuffer()}),fetch("https://raw.githubusercontent.com/notofonts/noto-fonts/main/hinted/ttf/NotoSans/NotoSans-Bold.ttf",{signal:AbortSignal.timeout(10_000)}).then(r=>{if(!r.ok)throw new Error("FONT_FETCH_FAILED");return r.arrayBuffer()})]);const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);const regular=await pdf.embedFont(fontBytes,{subset:true});const bold=await pdf.embedFont(boldBytes,{subset:true});
 const W=595.28,H=841.89,margin=48,width=W-margin*2;let page=pdf.addPage([W,H]);let y=H-52;const newPage=()=>{page=pdf.addPage([W,H]);y=H-52};const ensure=(need:number)=>{if(y<need)newPage()};const draw=(s:string,size=11,f=regular)=>{ensure(size+12);page.drawText(s,{x:margin,y,size,font:f,color:rgb(.08,.08,.08)});y-=size+7};
 page.drawText("STAGEPULSE",{x:margin,y,size:24,font:bold,color:rgb(.95,.58,.02)});y-=36;draw(`Teklif: ${o.quote_number||""}`,12,bold);y-=5;
 for(const block of [[`Müşteri: ${o.name||""}`,`Firma: ${o.company||""}`,`Telefon: ${o.phone||""}`,`E-posta: ${o.email||""}`],[`Etkinlik: ${o.event_type||o.type||""}`,`Tarih: ${o.event_date||""}`,`Lokasyon: ${o.location||""}`]]){const hgt=block.length*18+16;ensure(hgt+20);page.drawRectangle({x:margin,y:y-hgt+10,width,height:hgt,borderWidth:1,borderColor:rgb(.82,.82,.82),color:rgb(.98,.98,.98)});y-=2;for(const line of block)draw(line,10);y-=12}
 draw("Teklif kalemleri",13,bold);y-=2;page.drawText("Açıklama",{x:margin,y,size:9,font:bold});page.drawText("Adet",{x:margin+285,y,size:9,font:bold});page.drawText("Birim",{x:margin+335,y,size:9,font:bold});page.drawText("Toplam",{x:margin+425,y,size:9,font:bold});y-=17;
 for(const item of items as any[]){const lines=wrap(String(item.description||""),regular,9,275);const h=Math.max(18,lines.length*12+14);ensure(h+25);lines.forEach((line,i)=>page.drawText(line,{x:margin,y:y-i*12,size:9,font:regular}));page.drawText(String(Number(item.quantity)||0),{x:margin+285,y,size:9,font:regular});page.drawText(money(item.unit_price),{x:margin+335,y,size:9,font:regular});page.drawText(money(item.total),{x:margin+425,y,size:9,font:regular});y-=Math.max(18,lines.length*12+6);page.drawLine({start:{x:margin,y},end:{x:margin+width,y},thickness:.5,color:rgb(.85,.85,.85)});y-=8}
 ensure(100);page.drawText(`Personel: ${Number(o.crew_count)||0}`,{x:margin,y,size:11,font:bold});y-=26;page.drawText(`Toplam: ${money(o.total)}`,{x:margin,y,size:17,font:bold,color:rgb(.95,.58,.02)});y-=30;
 const supported=photos.filter((p:any)=>p?.mime_type==='image/jpeg'||p?.mime_type==='image/png');if(supported.length){ensure(170);draw("Ekli fotoğraflar",13,bold);for(const p of supported){try{const signed=await db.storage.from("offer-assets").createSignedUrl(p.storage_path,600);if(signed.error||!signed.data?.signedUrl)continue;const r=await fetch(signed.data.signedUrl,{signal:AbortSignal.timeout(10_000)});if(!r.ok)continue;const buf=await r.arrayBuffer();const img=p.mime_type==='image/png'?await pdf.embedPng(buf):await pdf.embedJpg(buf);const maxW=width,maxH=260,scale=Math.min(maxW/img.width,maxH/img.height,1);const iw=img.width*scale,ih=img.height*scale;ensure(ih+35);page.drawImage(img,{x:margin+(width-iw)/2,y:y-ih,width:iw,height:ih});y-=ih+12;page.drawText(String(p.file_name||"Fotoğraf"),{x:margin,y,size:8,font:regular,color:rgb(.35,.35,.35)});y-=18}catch(_){} }}
 ensure(35);page.drawText("Bu belge Stagepulse teklif sistemi tarafından oluşturulmuştur.",{x:margin,y,size:8,font:regular,color:rgb(.35,.35,.35)});const bytes=await pdf.save();const bytesBuffer=new Uint8Array(bytes).buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;const path=`offers/${oid}/stagepulse-${o.quote_number||oid}-${Date.now()}.pdf`;const up=await db.storage.from("offer-pdfs").upload(path,new Blob([bytesBuffer],{type:"application/pdf"}),{contentType:"application/pdf",upsert:false});if(up.error){console.error("offer-pdf storage upload failed",up.error);return json({error:"PDF kaydedilemedi."},500);}const dg=await crypto.subtle.digest("SHA-256",bytesBuffer);const sha256=Array.from(new Uint8Array(dg)).map(x=>x.toString(16).padStart(2,"0")).join("");const {data:latest}=await db.from("offer_pdf_assets").select("version_no").eq("offer_id",oid).order("version_no",{ascending:false}).limit(1);const v=(latest?.[0]?.version_no||0)+1;await db.from("offer_pdf_assets").update({is_current:false,updated_at:new Date().toISOString()}).eq("offer_id",oid);const fileName=`stagepulse-${o.quote_number||oid}.pdf`;const ins=await db.from("offer_pdf_assets").insert({offer_id:oid,storage_path:path,file_name:fileName,mime_type:"application/pdf",size_bytes:bytes.byteLength,sha256,version_no:v,is_current:true,customer_visible:true,created_by:ud.user.id});if(ins.error){console.error("offer-pdf asset insert failed",ins.error);return json({error:"PDF kaydı oluşturulamadı."},500);}return json({ok:true,path,file_name:fileName,version_no:v});
}catch(e){console.error(e);return json({error:"İşlem başarısız."},500)}});
