import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const ALLOWED=new Set(["https://stagepulse.com.tr","https://www.stagepulse.com.tr"]);
class PublicError extends Error{constructor(message:string,readonly status:number){super(message);this.name="PublicError";}}
const headers=(req:Request)=>({"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":ALLOWED.has(req.headers.get("origin")||"")?(req.headers.get("origin")||""):"https://stagepulse.com.tr","Vary":"Origin","Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Cache-Control":"no-store"});
const out=(req:Request,b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:headers(req)});
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
async function user(req:Request){const a=req.headers.get("authorization")||"";if(!a.toLowerCase().startsWith("bearer "))throw new PublicError("Oturum gerekli.",401);const {data,error}=await db.auth.getUser(a.slice(7).trim());if(error||!data.user)throw new PublicError("Oturum geçersiz.",401);return data.user;}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:headers(req)});if(req.method!=="POST")return out(req,{error:"Method Not Allowed"},405);try{const u=await user(req);const {data:m,error:me}=await db.from("org_memberships").select("user_id,active,role:role_id(code,name,tier,is_admin_role,can_manage_children),position:position_id(code,name),department:department_id(id,code,name),region:region_id(id,code,name),manager_user_id").eq("user_id",u.id).eq("active",true).maybeSingle();if(me)throw me;if(!m)throw new PublicError("Aktif organizasyon üyeliği bulunamadı.",403);const role=Array.isArray((m as any).role)?(m as any).role?.[0]:(m as any).role;const superAdmin=role?.code==="super_admin"||role?.code==="owner"||((role?.is_admin_role===true)&&Number(role?.tier)<=1);let capabilities:any[]=[];if(superAdmin){const {data:c,error:ce}=await db.from("admin_capabilities").select("key,name,category,description").eq("active",true).order("category").order("key");if(ce)throw ce;capabilities=c||[];}else{const {data:g,error:ge}=await db.from("admin_capability_grants").select("capability_key").eq("user_id",u.id).eq("enabled",true).order("capability_key");if(ge)throw ge;const keys=(g||[]).map((x:any)=>x.capability_key).filter(Boolean);if(keys.length){const {data:c,error:ce}=await db.from("admin_capabilities").select("key,name,category,description").in("key",keys).eq("active",true);if(ce)throw ce;capabilities=c||[];}}return out(req,{user:{id:u.id,email:u.email,username:u.user_metadata?.username||u.email?.split("@")[0]||"",display_name:u.user_metadata?.display_name||u.user_metadata?.full_name||"",role:role?.code||"",active:true},membership:m,permissions:Object.fromEntries(capabilities.map((x:any)=>[x.key,true])),capabilities});}catch(e){console.error("[staff-session]",e);return e instanceof PublicError?out(req,{error:e.message},e.status):out(req,{error:"Oturum bilgileri alınamadı."},500);}});
