/* Stagepulse Admin — single canonical entrypoint. */
/* 2026-09-02: canonical UI language, navigation state, actions and visual parity. */
(() => {
  'use strict';
  if (window.STAGEPULSE_ADMIN_BOOTSTRAPPED) return;
  window.STAGEPULSE_ADMIN_BOOTSTRAPPED = true;
  const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const db=()=>window.__stagepulseAdminClient||window.sb||window.supabaseClient||null;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  function fail(error){console.error('[stagepulse-admin-boot]',error);const c=q('#content');if(!c)return;c.innerHTML=`<div class="panel" role="alert" aria-live="assertive"><h2>Yönetim paneli yüklenemedi</h2><p>${navigator.onLine===false?'İnternet bağlantısı yok.':'Yönetim çekirdeği başlatılamadı.'}</p><button type="button" class="btn btn-primary" id="adminBootRetry">Yeniden dene</button></div>`;q('#adminBootRetry')?.addEventListener('click',()=>location.reload());}
  function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=false;s.onload=resolve;s.onerror=()=>reject(new Error(`Admin modülü yüklenemedi: ${src}`));document.body.appendChild(s);});}
  function injectStyle(){if(q('#stagepulse-admin-canonical-ui'))return;const s=document.createElement('style');s.id='stagepulse-admin-canonical-ui';s.textContent=`
    .admin-body .btn{border:1px solid #3b3e45!important;background:#17191e!important;color:#f4f4f4!important;font-weight:800!important;cursor:pointer!important;transition:.15s ease}.admin-body .btn:hover{border-color:#ffb000!important;transform:translateY(-1px);box-shadow:0 6px 18px rgba(255,176,0,.14)}.admin-body .btn-primary{background:#ffb000!important;border-color:#ffb000!important;color:#111!important}.admin-body .btn-primary:hover{background:#ffc12a!important;border-color:#ffc12a!important}
    .admin-body .admin-card,.admin-body .card,.admin-body .panel{background:#11151b!important;border:1px solid #2b3039!important;color:#f4f4f4!important;box-shadow:0 10px 30px rgba(0,0,0,.16)}.admin-body .cards{gap:14px!important}.admin-body .card-label,.admin-body .muted,.admin-body .subtle{color:#aeb5c0!important}.admin-body .card-value,.admin-body .metric,.admin-body h1,.admin-body h2,.admin-body h3{color:#fff!important}
    .admin-body .admin-table,.admin-body .data-table{width:100%!important;border-collapse:separate!important;border-spacing:0!important;background:#11151b!important;color:#e8ebf0!important;border:1px solid #2b3039!important;border-radius:12px!important;overflow:hidden!important}.admin-body .admin-table th,.admin-body .data-table th{background:#181c23!important;color:#aeb5c0!important;border-bottom:1px solid #343a45!important;padding:12px 13px!important;text-align:left!important;font-weight:900!important;white-space:nowrap}.admin-body .admin-table td,.admin-body .data-table td{background:#11151b!important;color:#e8ebf0!important;border-bottom:1px solid #252a32!important;padding:11px 13px!important;vertical-align:middle!important}.admin-body .admin-table tbody tr:nth-child(even) td,.admin-body .data-table tbody tr:nth-child(even) td{background:#13171e!important}.admin-body .admin-table tbody tr:hover td,.admin-body .data-table tbody tr:hover td{background:#191e26!important}
    .admin-body .status{display:inline-flex!important;align-items:center;justify-content:center;padding:4px 9px!important;border-radius:999px!important;border:1px solid #3b4048!important;font-size:11px!important;font-weight:900!important;white-space:nowrap}.admin-body .status.new,.admin-body .status.pending{color:#ffd166!important;background:rgba(255,176,0,.12)!important;border-color:#6b5000!important}.admin-body .status.reviewing{color:#c7a7ff!important;background:rgba(109,93,252,.12)!important;border-color:#4d3a9a!important}.admin-body .status.sent,.admin-body .status.preparing{color:#75aaff!important;background:rgba(93,140,255,.12)!important;border-color:#34578f!important}.admin-body .status.accepted,.admin-body .status.paid,.admin-body .status.active{color:#6ee7a0!important;background:rgba(0,214,143,.12)!important;border-color:#245439!important}.admin-body .status.rejected,.admin-body .status.cancelled,.admin-body .status.inactive,.admin-body .status.overdue{color:#ff7777!important;background:rgba(255,92,122,.12)!important;border-color:#633030!important}
    .admin-body .staff-card,.admin-body .org-member-row,.admin-body .rbac-member-list,.admin-body .org-members,.admin-body .sp-media-card,.admin-body .sp-inv-card,.admin-body .sp-staff-modal,.admin-body .modal-card{background:#11151b!important;border:1px solid #2b3039!important;color:#e8ebf0!important;border-radius:14px!important;box-shadow:0 8px 24px rgba(0,0,0,.18)!important}.admin-body .staff-card{border-top:3px solid #ffb000!important}.admin-body .staff-card:nth-child(3n){border-top-color:#00d68f!important}.admin-body .staff-card:nth-child(3n+2){border-top-color:#5d8cff!important}.admin-body .org-member-row:hover,.admin-body .rbac-row:hover,.admin-body .sp-media-card:hover,.admin-body .sp-inv-card:hover{border-color:#ffb000!important;background:#171b22!important}.admin-body .staff-card button,.admin-body .org-member-row button,.admin-body .rbac-member-list button,.admin-body .sp-media-card button,.admin-body .sp-inv-card button{border:1px solid #3b3e45!important;background:#191d24!important;color:#f4f4f4!important;border-radius:9px!important;font-weight:800!important;cursor:pointer!important}.admin-body .staff-card button:hover,.admin-body .org-member-row button:hover,.admin-body .rbac-member-list button:hover,.admin-body .sp-media-card button:hover,.admin-body .sp-inv-card button:hover{background:#ffb000!important;border-color:#ffb000!important;color:#111!important}
    .admin-body .sp-runtime-actions{white-space:nowrap!important;text-align:right!important}.admin-body .sp-runtime-edit,.admin-body .sp-runtime-delete{display:inline-flex!important;align-items:center;justify-content:center;min-width:84px!important;margin-left:6px!important;padding:8px 11px!important;border-radius:9px!important;font-weight:900!important}.admin-body .sp-runtime-edit{background:#ffb000!important;color:#111!important;border:1px solid #ffb000!important}.admin-body .sp-runtime-delete{background:#32171b!important;color:#ff8c9f!important;border:1px solid #633030!important}.admin-body .sp-runtime-delete:hover{background:#ff5c7a!important;color:#21070c!important;border-color:#ff5c7a!important}
    .admin-body .sp-cc-card,.admin-body .sp-ai-card{background:#12161d!important;border-color:#2b3039!important;color:#e8ebf0!important}.admin-body .sp-cc-tabs button,.admin-body .tabs button,.admin-body .tab-list button{background:#171b22!important;color:#cfd3db!important;border:1px solid #2b3039!important;border-radius:9px!important;font-weight:800!important}.admin-body .sp-cc-tabs button.active,.admin-body .tabs button.active,.admin-body .tab-list button.active{background:#ffb000!important;color:#111!important;border-color:#ffb000!important}.admin-body .sp-ai-approval-actions{display:flex!important;gap:8px!important;flex-wrap:wrap!important}.admin-body .sp-ai-approval-actions .ok{background:#00d68f!important;color:#06150f!important;border-color:#00d68f!important}.admin-body .sp-ai-approval-actions .no{background:#ff5c7a!important;color:#21070c!important;border-color:#ff5c7a!important}
    .admin-body input,.admin-body select,.admin-body textarea{background:#0c0f14!important;color:#f4f4f4!important;border:1px solid #343a45!important;border-radius:9px!important}.admin-body input:focus,.admin-body select:focus,.admin-body textarea:focus{border-color:#ffb000!important;outline:none!important;box-shadow:0 0 0 2px rgba(255,176,0,.12)!important}
    .sp-runtime-modal{position:fixed;inset:0;z-index:10050;display:flex;align-items:center;justify-content:center;padding:14px;background:rgba(0,0,0,.78);backdrop-filter:blur(5px)}.sp-runtime-modal-card{width:min(680px,100%);max-height:92svh;overflow:auto;background:#11151b;color:#fff;border:1px solid #343a45;border-radius:16px;padding:18px;box-shadow:0 25px 80px rgba(0,0,0,.55)}.sp-runtime-modal-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.sp-runtime-modal-grid label{display:grid;gap:5px;color:#aeb5c0;font-size:12px;font-weight:800}.sp-runtime-modal-grid input{box-sizing:border-box;width:100%;padding:10px}.sp-runtime-modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px;padding-top:14px;border-top:1px solid #2b3039}@media(max-width:700px){.sp-runtime-modal-grid{grid-template-columns:1fr}.admin-body .sp-runtime-edit,.admin-body .sp-runtime-delete{width:100%;margin:4px 0 0!important}.admin-body .sp-runtime-actions{white-space:normal!important}}
  `;document.head.appendChild(s);}
  const words={pending:'Bekliyor',offer_change:'Teklif değişikliği',offer_update:'Teklif güncellendi',staff_deleted:'Personel silindi',staff_updated:'Personel güncellendi',staff_permissions_updated:'Personel yetkileri güncellendi',system:'Sistem',Optimize:'Optimize Et',optimize:'Optimize Et',open:'Aç',Open:'Aç',edit:'Düzenle',Edit:'Düzenle',delete:'Sil',Delete:'Sil',active:'Aktif',inactive:'Pasif',paid:'Ödendi',overdue:'Gecikmiş',deposit:'Kapora',partial:'Kısmi',accepted:'Kabul',rejected:'Reddedildi',reviewing:'İncelemede',preparing:'Hazırlanıyor',sent:'Gönderildi',new:'Yeni'};
  function translate(root=document){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];let n;while((n=w.nextNode()))nodes.push(n);nodes.forEach(node=>{const t=(node.nodeValue||'').trim();const k=Object.keys(words).find(x=>x.toLowerCase()===t.toLowerCase());if(k)node.nodeValue=node.nodeValue.replace(t,words[k]);});}
  function activeNav(){const hash=(location.hash||'#dashboard').replace(/^#/,'').split('?')[0].toLowerCase();const buttons=qa('#sideNav button,#sideNav a');buttons.forEach(b=>{b.classList.remove('active');b.removeAttribute('aria-current');});let target=hash;const direct=buttons.find(b=>String(b.dataset.view||'').toLowerCase()===target);if(direct){direct.classList.add('active');direct.setAttribute('aria-current','page');return;}const tests={rbac:['rol','yetki'],organization:['şirket organizasyonu'],scope:['yönetim kapsamım'],accounts:['yönetici hesapları']};const hit=tests[target]?buttons.find(b=>tests[target].some(s=>(b.textContent||'').trim().toLowerCase().includes(s))):null;if(hit){hit.classList.add('active');hit.setAttribute('aria-current','page');}}
  function statusColors(){qa('.status').forEach(el=>{const t=(el.textContent||'').trim().toLowerCase();const map={pending:'pending',bekliyor:'pending',new:'new',yeni:'new',reviewing:'reviewing',incelemede:'reviewing',preparing:'preparing',hazırlanıyor:'preparing',sent:'sent',gönderildi:'sent',accepted:'accepted',kabul:'accepted',paid:'paid',ödendi:'paid',active:'active',aktif:'active',rejected:'rejected',reddedildi:'rejected',cancelled:'cancelled',iptal:'cancelled',inactive:'inactive',pasif:'inactive',overdue:'overdue',gecikmiş:'overdue'};el.className='status '+(map[t]||'');});}
  const tablesByView={customers:'customers',pricing:'services',settlements:'settlements',calendar:'jobs',finance:'payments',personnel:'org_memberships'};
  const fieldSpecs={customers:{table:'customers',title:'Müşteri düzenle',fields:[['name','Müşteri'],['company','Firma'],['phone','Telefon'],['email','E-posta'],['notes','Notlar'],['active','Aktif']]},pricing:{table:'services',title:'Fiyatlandırma düzenle',fields:[['name','Hizmet'],['description','Açıklama'],['active','Aktif']]},settlements:{table:'settlements',title:'Gelir · gider düzenle',fields:[['title','İş'],['event_date','Tarih'],['agreed_amount','Anlaşılan'],['expense_amount','Gider'],['status','Durum'],['notes','Notlar']]},calendar:{table:'jobs',title:'İş · takvim düzenle',fields:[['title','İş'],['location','Konum'],['event_start_at','Etkinlik'],['status','Durum'],['notes','Notlar']]},finance:{table:'payments',title:'Ödeme düzenle',fields:[['description','Açıklama'],['amount','Tutar'],['due_date','Vade'],['paid_at','Ödeme tarihi'],['status','Durum']]}};
  function openEditor(view,id){const spec=fieldSpecs[view],client=db();if(!spec||!client||!id)return;client.from(spec.table).select('*').eq('id',id).maybeSingle().then(({data,error})=>{if(error||!data){window.toast?.(error?.message||'Kayıt bulunamadı.',false);return;}q('#spRuntimeEditor')?.remove();const w=document.createElement('div');w.id='spRuntimeEditor';w.className='sp-runtime-modal';w.innerHTML=`<div class="sp-runtime-modal-card"><h2>${esc(spec.title)}</h2><div class="sp-runtime-modal-grid">${spec.fields.map(([k,l])=>`<label>${esc(l)}<input data-k="${k}" type="${k==='active'?'checkbox':'text'}" ${k==='active'?(data[k]===true?'checked':''):`value="${esc(data[k]??'')}"`}></label>`).join('')}</div><div class="sp-runtime-modal-actions"><button type="button" class="btn" data-cancel>Vazgeç</button><button type="button" class="btn btn-primary" data-save>Kaydet</button></div></div>`;document.body.appendChild(w);q('[data-cancel]',w).onclick=()=>w.remove();q('[data-save]',w).onclick=async()=>{const patch={};qa('[data-k]',w).forEach(i=>patch[i.dataset.k]=i.type==='checkbox'?i.checked:(i.value.trim()||null));const res=await client.from(spec.table).update(patch).eq('id',id);if(res.error){window.toast?.(res.error.message,false);return;}w.remove();window.toast?.('Kaydedildi.',true);setTimeout(()=>location.reload(),120);};});}
  async function deleteRow(view,id){const table=tablesByView[view],client=db();if(!table||!client||!id)return;if(!confirm('Bu kaydı silmek istediğinize emin misiniz?'))return;const {error}=await client.from(table).delete().eq('id',id);if(error){window.toast?.(error.message||'Silme işlemi başarısız.',false);return;}window.toast?.('Silindi.',true);setTimeout(()=>location.reload(),120);}
  async function addActions(){const view=(location.hash||'#dashboard').slice(1).split('?')[0].toLowerCase(),tableName=tablesByView[view],client=db();if(!tableName||!client)return;const tables=qa('.admin-table').filter(t=>!t.dataset.spActions);if(!tables.length)return;let records=[];try{let x=client.from(tableName).select('id');if(view==='pricing')x=x.order('name',{ascending:true});else if(view==='calendar')x=x.order('event_start_at',{ascending:true});else x=x.order('created_at',{ascending:false});const r=await x.limit(250);records=r.data||[];}catch(e){console.warn('[stagepulse-admin-actions]',e);return;}tables.forEach(table=>{table.dataset.spActions='1';const head=table.tHead?.rows[0];if(head&&!head.querySelector('.sp-runtime-actions')){const th=document.createElement('th');th.className='sp-runtime-actions';th.textContent='İşlem';head.appendChild(th);}qa('tbody tr',table).forEach((tr,i)=>{const id=tr.dataset.spRowId||tr.querySelector('[data-id]')?.dataset.id||records[i]?.id;if(!id)return;tr.dataset.spRowId=id;const td=document.createElement('td');td.className='sp-runtime-actions';if(!tr.querySelector('.sp-runtime-edit')){const e=document.createElement('button');e.type='button';e.className='sp-runtime-edit';e.textContent='Düzenle';e.onclick=()=>openEditor(view,id);td.appendChild(e);}if(view!=='notifications'&&!tr.querySelector('.sp-runtime-delete')){const d=document.createElement('button');d.type='button';d.className='sp-runtime-delete';d.textContent='Sil';d.onclick=()=>deleteRow(view,id);td.appendChild(d);}if(td.childElementCount)tr.appendChild(td);});});}
  function polish(){translate();statusColors();activeNav();setTimeout(addActions,80);}
  const observer=new MutationObserver(()=>polish());
  async function boot(){try{await loadScript('admin-bundle.js?v=20260902-webfix10');if(typeof window.loadView!=='function')throw new Error('Canonical admin bundle did not expose loadView');try{await loadScript('notifications-tools.js?v=20260902-notify1');}catch(e){console.warn('[stagepulse-admin-notifications]',e)}injectStyle();const c=q('#content');if(c)observer.observe(c,{childList:true,subtree:true});polish();window.addEventListener('hashchange',()=>setTimeout(polish,50));window.STAGEPULSE_ADMIN_READY=true;window.dispatchEvent(new CustomEvent('stagepulse:admin-ready'));window.dispatchEvent(new CustomEvent('stagepulse-admin-ready'));}catch(e){fail(e)}}
  window.addEventListener('online',()=>{if(!window.STAGEPULSE_ADMIN_READY)location.reload()},{once:true});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();