/* Stagepulse Admin — single canonical runtime. */
(() => {
  'use strict';
  if (window.STAGEPULSE_ADMIN_BOOTSTRAPPED) return;
  window.STAGEPULSE_ADMIN_BOOTSTRAPPED = true;
  const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const db=()=>window.__stagepulseAdminClient||window.sb||window.supabaseClient||null;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const words={pending:'Bekliyor',offer_change:'Teklif değişikliği',offer_update:'Teklif güncellendi',staff_deleted:'Personel silindi',staff_updated:'Personel güncellendi',staff_permissions_updated:'Personel yetkileri güncellendi',system:'Sistem',open:'Aç',edit:'Düzenle',Edit:'Düzenle',delete:'Sil',Delete:'Sil',active:'Aktif',inactive:'Pasif',paid:'Ödendi',overdue:'Gecikmiş',deposit:'Kapora',partial:'Kısmi',accepted:'Kabul',rejected:'Reddedildi',reviewing:'İncelemede',preparing:'Hazırlanıyor',sent:'Gönderildi',new:'Yeni'};
  const tablesByView={customers:'customers',pricing:'services',settlements:'settlements',calendar:'jobs',finance:'payments'};
  const fieldSpecs={
    customers:{table:'customers',entity:'customers',title:'Müşteri düzenle',fields:[['name','Müşteri','text'],['company','Firma','text'],['phone','Telefon','text'],['email','E-posta','email'],['notes','Notlar','textarea'],['active','Aktif','checkbox']]},
    pricing:{table:'services',entity:'services',title:'Fiyatlandırma düzenle',fields:[['name','Hizmet','text'],['description','Açıklama','textarea'],['base_price','Temel fiyat','number'],['active','Aktif','checkbox']]},
    settlements:{table:'settlements',entity:'settlements',title:'Gelir · gider düzenle',fields:[['title','İş','text'],['event_date','Tarih','date'],['agreed_amount','Anlaşılan','number'],['expense_amount','Gider','number'],['status','Durum','text'],['notes','Notlar','textarea']]},
    calendar:{table:'jobs',entity:'jobs',title:'İş · takvim düzenle',fields:[['title','İş','text'],['location','Konum','text'],['event_start_at','Etkinlik','datetime-local'],['status','Durum','text'],['notes','Notlar','textarea']]},
    finance:{table:'payments',entity:'payments',title:'Ödeme düzenle',fields:[['description','Açıklama','text'],['amount','Tutar','number'],['due_date','Vade','date'],['paid_at','Ödeme tarihi','datetime-local'],['status','Durum','text']]}
  };
  function injectStyle(){if(q('#stagepulse-admin-canonical-ui'))return;const s=document.createElement('style');s.id='stagepulse-admin-canonical-ui';s.textContent=`
    .admin-body .btn{border:1px solid #3b3e45!important;background:#17191e!important;color:#f4f4f4!important;font-weight:800!important;cursor:pointer!important;transition:.15s ease}.admin-body .btn:hover{border-color:#ffb000!important;transform:translateY(-1px)}.admin-body .btn-primary{background:#ffb000!important;border-color:#ffb000!important;color:#111!important}
    .admin-body .admin-card,.admin-body .card,.admin-body .panel{background:#11151b!important;border:1px solid #2b3039!important;color:#f4f4f4!important}.admin-body .admin-table,.admin-body .data-table{width:100%!important;border-collapse:separate!important;border-spacing:0!important;background:#11151b!important;color:#e8ebf0!important;border:1px solid #2b3039!important;border-radius:12px!important;overflow:hidden!important}.admin-body .admin-table th,.admin-body .data-table th{background:#181c23!important;color:#aeb5c0!important;border-bottom:1px solid #343a45!important;padding:12px 13px!important;text-align:left!important;font-weight:900!important}.admin-body .admin-table td,.admin-body .data-table td{background:#11151b!important;color:#e8ebf0!important;border-bottom:1px solid #252a32!important;padding:11px 13px!important;vertical-align:middle!important}.admin-body .admin-table tbody tr:hover td,.admin-body .data-table tbody tr:hover td{background:#191e26!important}
    .admin-body input,.admin-body select,.admin-body textarea{background:#0c0f14!important;color:#f4f4f4!important;border:1px solid #343a45!important;border-radius:9px!important}.admin-body input:focus,.admin-body select:focus,.admin-body textarea:focus{border-color:#ffb000!important;outline:none!important;box-shadow:0 0 0 2px rgba(255,176,0,.12)!important}.admin-body .sp-runtime-actions{white-space:nowrap!important;text-align:right!important}.admin-body .sp-runtime-edit{background:#ffb000!important;color:#111!important;border:1px solid #ffb000!important}.admin-body .sp-runtime-delete{background:#32171b!important;color:#ff8c9f!important;border:1px solid #633030!important}.admin-body .sp-runtime-edit,.admin-body .sp-runtime-delete{display:inline-flex!important;align-items:center;justify-content:center;min-width:84px!important;margin-left:6px!important;padding:8px 11px!important;border-radius:9px!important;font-weight:900!important}
    .sp-runtime-modal{position:fixed;inset:0;z-index:10050;display:flex;align-items:center;justify-content:center;padding:14px;background:rgba(0,0,0,.78);backdrop-filter:blur(5px)}.sp-runtime-modal-card{width:min(680px,100%);max-height:92svh;overflow:auto;background:#11151b;color:#fff;border:1px solid #343a45;border-radius:16px;padding:18px;box-shadow:0 25px 80px rgba(0,0,0,.55)}.sp-runtime-modal-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.sp-runtime-modal-grid label{display:grid;gap:5px;color:#aeb5c0;font-size:12px;font-weight:800}.sp-runtime-modal-grid input,.sp-runtime-modal-grid textarea{box-sizing:border-box;width:100%;padding:10px}.sp-runtime-modal-grid textarea{min-height:110px}.sp-runtime-modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px;padding-top:14px;border-top:1px solid #2b3039}@media(max-width:700px){.sp-runtime-modal-grid{grid-template-columns:1fr}.admin-body .sp-runtime-edit,.admin-body .sp-runtime-delete{width:100%;margin:4px 0 0!important}.admin-body .sp-runtime-actions{white-space:normal!important}}
  `;document.head.appendChild(s);}
  function translate(root=document){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];let n;while((n=w.nextNode()))nodes.push(n);nodes.forEach(node=>{const t=(node.nodeValue||'').trim();const k=Object.keys(words).find(x=>x.toLowerCase()===t.toLowerCase());if(k)node.nodeValue=node.nodeValue.replace(t,words[k]);});}
  function activeNav(){const hash=(location.hash||'#dashboard').replace(/^#/,'').split('?')[0].toLowerCase();qa('#sideNav button,#sideNav a').forEach(b=>{b.classList.remove('active');b.removeAttribute('aria-current');});const direct=qa('#sideNav button,#sideNav a').find(b=>String(b.dataset.view||'').toLowerCase()===hash);if(direct){direct.classList.add('active');direct.setAttribute('aria-current','page');}}
  function statusColors(){const map={pending:'pending',bekliyor:'pending',new:'new',yeni:'new',reviewing:'reviewing',incelemede:'reviewing',preparing:'preparing',hazırlanıyor:'preparing',sent:'sent',gönderildi:'sent',accepted:'accepted',kabul:'accepted',paid:'paid',ödendi:'paid',active:'active',aktif:'active',rejected:'rejected',reddedildi:'rejected',cancelled:'cancelled',iptal:'cancelled',inactive:'inactive',pasif:'inactive',overdue:'overdue',gecikmiş:'overdue'};qa('.status').forEach(el=>{const t=(el.textContent||'').trim().toLowerCase();el.className='status '+(map[t]||'');});}
  async function command(action,entity,id,payload={}){const client=db();if(!client)throw new Error('Supabase bağlantısı hazır değil.');const {data,error}=await client.rpc('stagepulse_command_action',{p_action:action,p_entity:entity,p_id:id||null,p_payload:payload});if(error)throw error;return data;}
  function inputValue(field,value){if(field[2]==='checkbox')return value===true;if(field[2]==='datetime-local'&&value)return new Date(value).toISOString().slice(0,16);return value??'';}
  async function openEditor(view,id){const spec=fieldSpecs[view],client=db();if(!spec||!client||!id)return;const {data,error}=await client.from(spec.table).select('*').eq('id',id).maybeSingle();if(error||!data){window.toast?.(error?.message||'Kayıt bulunamadı.',false);return;}q('#spRuntimeEditor')?.remove();const w=document.createElement('div');w.id='spRuntimeEditor';w.className='sp-runtime-modal';w.innerHTML=`<div class="sp-runtime-modal-card"><h2>${esc(spec.title)}</h2><div class="sp-runtime-modal-grid">${spec.fields.map(f=>f[2]==='textarea'?`<label>${esc(f[1])}<textarea data-k="${esc(f[0])}">${esc(inputValue(f,data[f[0]]))}</textarea></label>`:`<label>${esc(f[1])}<input data-k="${esc(f[0])}" type="${esc(f[2])}" ${f[2]==='checkbox'?(data[f[0]]===true?'checked':''):`value="${esc(inputValue(f,data[f[0]]))}"`}></label>`).join('')}</div><div class="sp-runtime-modal-actions"><button type="button" class="btn" data-cancel>Vazgeç</button><button type="button" class="btn btn-primary" data-save>Kaydet</button></div></div>`;document.body.appendChild(w);q('[data-cancel]',w).onclick=()=>w.remove();q('[data-save]',w).onclick=async()=>{const patch={};qa('[data-k]',w).forEach(i=>{if(i.type==='checkbox')patch[i.dataset.k]=i.checked;else if(i.value.trim()!=='')patch[i.dataset.k]=i.value.trim();});const btn=q('[data-save]',w);btn.disabled=true;try{await command('update',spec.entity,id,patch);w.remove();window.toast?.('Kaydedildi.',true);setTimeout(()=>location.reload(),120);}catch(e){window.toast?.(e.message||'Kaydetme başarısız.',false);btn.disabled=false;}};}
  async function deleteRow(view,id){const entity=tablesByView[view];if(!entity||!id)return;if(!confirm('Bu kaydı silmek istediğinize emin misiniz?'))return;try{await command('delete',entity,id,{});window.toast?.('Silindi.',true);setTimeout(()=>location.reload(),120);}catch(e){window.toast?.(e.message||'Silme işlemi başarısız.',false);}}
  async function addActions(){const view=(location.hash||'#dashboard').slice(1).split('?')[0].toLowerCase(),tableName=tablesByView[view],client=db();if(!tableName||!client)return;const tables=qa('.admin-table').filter(t=>!t.dataset.spCanonicalActions);if(!tables.length)return;let query=client.from(tableName).select('id');query=view==='pricing'?query.order('name',{ascending:true}):query.order('created_at',{ascending:false});const {data,error}=await query.limit(250);if(error||!data)return;tables.forEach(table=>{qa('tbody tr',table).forEach((row,i)=>{const record=data[i];if(!record)return;const td=document.createElement('td');td.className='sp-runtime-actions';td.dataset.label='İşlem';td.innerHTML=`<button type="button" class="btn sp-runtime-edit" data-sp-edit="${esc(record.id)}">Düzenle</button><button type="button" class="btn sp-runtime-delete" data-sp-delete="${esc(record.id)}">Sil</button>`;row.appendChild(td);});table.dataset.spCanonicalActions='1';qa('[data-sp-edit]',table).forEach(b=>b.onclick=()=>openEditor(view,b.dataset.spEdit));qa('[data-sp-delete]',table).forEach(b=>b.onclick=()=>deleteRow(view,b.dataset.spDelete));});}
  function labelTables(){qa('.admin-table').forEach(t=>{const hs=qa('thead th',t).map(h=>(h.textContent||'').trim());qa('tbody tr',t).forEach(r=>qa(':scope > td',r).forEach((td,i)=>{if(hs[i])td.setAttribute('data-label',hs[i]);}));});}
  function refresh(){injectStyle();activeNav();translate();statusColors();labelTables();addActions().catch(e=>console.warn('[stagepulse-admin] canonical actions',e));}
  function fail(error){console.error('[stagepulse-admin]',error);const c=q('#content');if(!c)return;c.innerHTML=`<div class="panel" role="alert"><h2>Yönetim paneli yüklenemedi</h2><p>${esc(error?.message||'Yönetim çekirdeği başlatılamadı.')}</p><button type="button" class="btn btn-primary" id="adminBootRetry">Yeniden dene</button></div>`;q('#adminBootRetry')?.addEventListener('click',()=>location.reload());}
  function boot(){try{refresh();window.dispatchEvent(new Event('stagepulse-admin-ready'));window.dispatchEvent(new Event('stagepulse:admin-ready'));window.STAGEPULSE_CANONICAL_COMMANDS=true;const observer=new MutationObserver(()=>refresh());observer.observe(q('#content')||document.body,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(refresh,40));}catch(e){fail(e);}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
