/* Stagepulse Admin — canonical Auth + RBAC */
(() => {
  'use strict';
  const loginForm=document.getElementById('loginForm'),forgot=document.getElementById('forgotPasswordBtn'),errorBox=document.getElementById('loginError'),noticeBox=document.getElementById('resetNotice'),resetUrl=`${location.origin}/admin/`;
  const strong=p=>typeof p==='string'&&p.length>=10&&p.length<=128&&/[A-Za-zğüşıöçĞÜŞİÖÇ]/.test(p)&&/\d/.test(p);const R=window.STAGEPULSE_RUNTIME||{};const URL=(R.supabaseUrl||window.SUPABASE_URL||'').replace(/\/$/,'');const KEY=R.supabasePublishableKey||window.SUPABASE_KEY||'';const client=()=>window.StagepulseAdminSupabase?.getClient?.()||window.__stagepulseAdminClient||window.sb||window.supabaseClient||null;const sb=client();if(!sb)throw Error('Yönetici istemcisi hazır değil.');const adminLoginUrl=`${URL}/functions/v1/admin-login`;const edge=`${URL}/functions/v1/org-admin-control`;
  async function canonicalAdminLogin(username,password){const r=await fetch(adminLoginUrl,{method:'POST',headers:{'Content-Type':'application/json',apikey:KEY},body:JSON.stringify({action:'login',username:String(username||'').trim().toLowerCase(),password}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok||!j?.session?.access_token)throw new Error(j?.error||'Geçersiz kullanıcı adı veya şifre.');return j;}
  async function verifyAdminSession(session){if(!session?.access_token)throw new Error('Yönetici oturumu bulunamadı.');const r=await fetch(edge,{method:'POST',headers:{'Content-Type':'application/json',apikey:KEY,Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action:'my_context'}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok||!j.membership||j.membership.active!==true||j.is_admin!==true){await sb.auth.signOut().catch(()=>{});throw new Error('Bu hesap için aktif yönetim yetkisi bulunmuyor.');}window.__stagepulseAdminContext=j;return j;}
  async function authenticate(username,password){const login=await canonicalAdminLogin(username,password);const {error}=await sb.auth.setSession({access_token:login.session.access_token,refresh_token:login.session.refresh_token});if(error)throw new Error('Yönetici oturumu oluşturulamadı.');const current=await sb.auth.getSession();if(!current.data?.session)throw new Error('Yönetici oturumu oluşturulamadı.');const context=await verifyAdminSession(current.data.session);return {session:current.data.session,context};}
  async function forgotFlow(){forgot.disabled=true;if(noticeBox)noticeBox.textContent='Sıfırlama bağlantısı gönderiliyor…';if(errorBox)errorBox.textContent='';try{const email=document.getElementById('loginUsername')?.value?.trim().toLowerCase()||'';if(!email.includes('@'))throw new Error('Şifre sıfırlamak için kullanıcı adı alanına e-posta adresinizi yazın.');const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:resetUrl});if(error)throw error;if(noticeBox)noticeBox.textContent='Eğer bu e-posta kayıtlıysa, sıfırlama bağlantısı gönderildi.';}catch(e){if(errorBox)errorBox.textContent=e?.message||'Şifre sıfırlama başarısız.';if(noticeBox)noticeBox.textContent='';}finally{forgot.disabled=false;}}
  function resetModal(){document.getElementById('spResetModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="spResetModal"><div class="modal-card"><button class="close" type="button" id="spResetClose">×</button><div class="auth-mark">SP</div><h2>Yeni şifre</h2><p class="muted">En az 10 karakter, bir harf ve bir rakam kullanın.</p><label>Yeni şifre<input id="spNewPassword" type="password" minlength="10" autocomplete="new-password"></label><label>Yeni şifre tekrar<input id="spNewPassword2" type="password" minlength="10" autocomplete="new-password"></label><div class="modal-actions"><button class="btn btn-primary" id="spResetSave" type="button">Şifreyi güncelle</button></div><p id="spResetError" class="form-error"></p></div></div>`);document.getElementById('spResetClose')?.addEventListener('click',()=>document.getElementById('spResetModal')?.remove());document.getElementById('spResetSave')?.addEventListener('click',async()=>{const a=document.getElementById('spNewPassword')?.value||'',b=document.getElementById('spNewPassword2')?.value||'',e=document.getElementById('spResetError');if(!strong(a)){e.textContent='Şifre en az 10 karakter, bir harf ve bir rakam içermeli.';return;}if(a!==b){e.textContent='Şifreler eşleşmiyor.';return;}const {error}=await sb.auth.updateUser({password:a});if(error){e.textContent=error.message;return;}await sb.auth.signOut();document.getElementById('spResetModal')?.remove();if(noticeBox)noticeBox.textContent='Şifreniz güncellendi. Yeni şifrenizle giriş yapabilirsiniz.';});}
  async function loginV3(e){e.preventDefault();e.stopImmediatePropagation();const username=document.getElementById('loginUsername')?.value?.trim().toLowerCase()||'',password=document.getElementById('loginPassword')?.value||'';if(errorBox)errorBox.textContent='';if(noticeBox)noticeBox.textContent='';if(!username||!password){if(errorBox)errorBox.textContent='Kullanıcı adı ve şifre zorunludur.';return;}const btn=document.getElementById('loginBtn');if(btn){btn.disabled=true;btn.textContent='Giriş…';}try{const result=await authenticate(username,password);window.__stagepulseAdminContext=result.context;await window.guardAdminSession?.(result.session);}catch(ex){if(errorBox)errorBox.textContent=ex?.message||'Giriş başarısız.';}finally{if(btn){btn.disabled=false;btn.textContent='Giriş Yap';}}}
  window.guardAdminSession=async session=>{const context=await verifyAdminSession(session),login=document.getElementById('loginView'),app=document.getElementById('appView');if(login){login.classList.add('is-hidden');login.hidden=true;}if(app){app.classList.remove('is-hidden');app.hidden=false;}const m=context.membership||{},role=m.role||{},p=context.profile||{},adminUser=document.getElementById('adminUser'),adminName=document.getElementById('sideAdminName');if(adminUser)adminUser.textContent='@'+(p.username||session.user?.user_metadata?.username||session.user?.email?.split('@')[0]||'admin');if(adminName)adminName.textContent=p.display_name||session.user?.user_metadata?.display_name||session.user?.email?.split('@')[0]||role.name||'Yönetici';if(typeof window.loadView==='function')await window.loadView((location.hash||'#dashboard').slice(1)||'dashboard');return true;};
  forgot?.addEventListener('click',forgotFlow);loginForm?.addEventListener('submit',loginV3,true);sb.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY')resetModal();});
})();