/* Stagepulse admin — realtime sync + visual dashboard enhancements. */
(() => {
  if (!window.supabase) return;
  const client = window.supabase.createClient('https://mtjcqqrogjqaxkagwkti.supabase.co','sb_publishable_yR_HlWlFbYYq22tQmiB9LA_acq6bQi6');
  let channel=null,timer=null,observer=null;
  const currentView=()=> (location.hash||'#dashboard').slice(1)||'dashboard';
  const editing=()=>{const el=document.activeElement;return !!el&&/^(INPUT|TEXTAREA|SELECT)$/.test(el.tagName);};
  const refresh=()=>{timer=null;if(editing()){if(typeof window.toast==='function')window.toast('Yeni değişiklik geldi. Açık formu kaydettikten sonra ekran yenilenecek.',true);return;}const v=currentView();const btn=document.querySelector(`#sideNav button[data-view="${CSS.escape(v)}"]`);if(btn)btn.click();};
  const schedule=()=>{if(timer)clearTimeout(timer);timer=setTimeout(refresh,450);};
  const notify=p=>{const n=p?.new||{};if(n.title&&typeof window.toast==='function')window.toast(`${n.title}: ${n.body||''}`.trim(),true);if(currentView()==='notifications')schedule();};
  async function deleteAllNotifications(){if(!confirm('Tüm bildirimler kalıcı olarak silinsin mi? Bu işlem geri alınamaz.'))return;const {error}=await client.from('notifications').delete().not('id','is',null);if(error){if(typeof window.toast==='function')window.toast(error.message,false);return;}if(typeof window.toast==='function')window.toast('Tüm bildirimler silindi');if(typeof window.loadView==='function')window.loadView('notifications');}
  function enhanceNotifications(){if(currentView()!=='notifications')return;const content=document.querySelector('#content');if(!content)return;const head=content.querySelector('.page-head');if(!head||head.dataset.spEnhanced==='1')return;head.dataset.spEnhanced='1';const actions=document.createElement('div');actions.className='sp-notification-toolbar';const count=document.createElement('div');count.className='sp-notification-count';count.innerHTML=`Bildirim merkezi · <b>${content.querySelectorAll('.row-item').length}</b> kayıt`;const mark=document.createElement('button');mark.className='btn';mark.textContent='✓ Tümünü okundu say';mark.onclick=()=>window.markAllNotificationsRead?.();const del=document.createElement('button');del.className='btn btn-danger sp-danger-all';del.textContent='⌫ Tümünü sil';del.onclick=deleteAllNotifications;actions.append(count,mark,del);head.parentNode.insertBefore(actions,head.nextSibling);const panel=content.querySelector('.panel');if(panel){const rows=[...panel.querySelectorAll('.row-item')];if(rows.length){panel.classList.add('notifications-grid');rows.forEach(r=>{r.classList.add('notification-card');if(r.style.opacity!=='0.65')r.classList.add('unread');const dot=document.createElement('i');dot.className='notification-dot';r.prepend(dot);});}}}
  async function enhanceAnalytics(){if(currentView()!=='analytics')return;const content=document.querySelector('#content');if(!content||content.dataset.spAnalytics==='1')return;const chart=content.querySelector('.chart');if(!chart)return;content.dataset.spAnalytics='1';const offerRows=(typeof offers!=='undefined'&&Array.isArray(offers))?offers:[];const accepted=offerRows.filter(x=>x.status==='accepted').length;const rejected=offerRows.filter(x=>['rejected','cancelled','expired'].includes(x.status)).length;const pending=Math.max(0,offerRows.length-accepted-rejected);const monthMap={};offerRows.forEach(o=>{const k=(o.created_at||'').slice(0,7);if(k)monthMap[k]=(monthMap[k]||0)+1;});const keys=Object.keys(monthMap).sort().slice(-12);const max=Math.max(1,...keys.map(k=>monthMap[k]));const flow=document.createElement('div');flow.className='sp-flow';flow.innerHTML=`<div class="sp-flow-step" style="--flow:#00d9ff"><b>Müşteri</b><span>${offerRows.length} teklif kaynağı</span></div><div class="sp-flow-arrow">→</div><div class="sp-flow-step" style="--flow:#7c4dff"><b>Teklif</b><span>${offerRows.length} toplam teklif</span></div><div class="sp-flow-arrow">→</div><div class="sp-flow-step" style="--flow:#00e5a0"><b>Kabul</b><span>${accepted} iş kazanıldı</span></div>`;const grid=document.createElement('div');grid.className='sp-analytics-grid';const monthly=document.createElement('div');monthly.className='panel';monthly.innerHTML=`<div class="panel-head"><h3>Aylık teklif trafiği</h3><span class="muted small">Son 12 ay</span></div><div class="sp-mini-bars">${keys.map(k=>`<div><div class="sp-mini-bar" style="height:${Math.max(8,Math.round((monthMap[k]/max)*118))}px"></div><div class="sp-mini-label">${k.slice(5)}</div></div>`).join('')||'<span class="muted">Henüz veri yok</span>'}</div>`;const status=document.createElement('div');status.className='panel';status.innerHTML=`<div class="panel-head"><h3>Teklif durumu</h3><span class="muted small">Canlı veri</span></div><div class="sp-stat-list"><div class="sp-stat"><span>Bekleyen / aktif</span><b>${pending}</b></div><div class="sp-stat"><span>Kabul edilen</span><b style="color:#69df91">${accepted}</b></div><div class="sp-stat"><span>Red / iptal</span><b style="color:#ff7373">${rejected}</b></div><div class="sp-stat"><span>Dönüşüm</span><b>${offerRows.length?Math.round(accepted/offerRows.length*100):0}%</b></div></div>`;grid.append(monthly,status);const oldPanel=chart.closest('.panel');if(oldPanel)oldPanel.replaceWith(grid);const pageHead=content.querySelector('.page-head');if(pageHead)pageHead.insertAdjacentElement('afterend',flow);}
  function enhance(){try{enhanceNotifications();enhanceAnalytics();}catch(e){console.warn('Stagepulse UI enhancement failed:',e);}}
  async function start(){try{const {data}=await client.auth.getUser();const uid=data?.user?.id;if(!uid)return;if(channel)await client.removeChannel(channel);channel=client.channel(`stagepulse-admin-live-${uid}`).on('postgres_changes',{event:'*',schema:'public',table:'teklifler'},()=>{enhance();schedule();}).on('postgres_changes',{event:'*',schema:'public',table:'jobs'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'equipment'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'customers'},()=>{enhance();schedule();}).on('postgres_changes',{event:'*',schema:'public',table:'settlements'},()=>{enhance();schedule();}).on('postgres_changes',{event:'*',schema:'public',table:'payments'},()=>{enhance();schedule();}).on('postgres_changes',{event:'*',schema:'public',table:'services'},()=>{enhance();schedule();}).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`recipient_user_id=eq.${uid}`},notify).subscribe();}catch(e){console.warn('Stagepulse realtime admin sync failed:',e);}}
  window.addEventListener('load',()=>{setTimeout(start,1200);setTimeout(enhance,1600);setTimeout(enhance,3000);});window.addEventListener('hashchange',()=>setTimeout(enhance,120));document.addEventListener('visibilitychange',()=>{if(!document.hidden){start();setTimeout(enhance,250);}});document.addEventListener('DOMContentLoaded',()=>{const root=document.querySelector('#content');if(root){observer=new MutationObserver(()=>{if(currentView()==='notifications'||currentView()==='analytics')setTimeout(enhance,30);});observer.observe(root,{childList:true,subtree:true});}});window.stagepulseDeleteAllNotifications=deleteAllNotifications;
})();