import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const ALLOWED=new Set(["https://stagepulse.com.tr","https://www.stagepulse.com.tr"]);
const headers=(req:Request)=>{const o=req.headers.get("origin")||"";return {"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":ALLOWED.has(o)?o:"https://stagepulse.com.tr","Vary":"Origin","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Cache-Control":"no-store"}};
const out=(req:Request,b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:headers(req)});
const url=Deno.env.get("SUPABASE_URL")!;const key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const admin=createClient(url,key,{auth:{persistSession:false}});
async function requireAdmin(req:Request){const a=req.headers.get("authorization")||"";if(!a.toLowerCase().startsWith("bearer "))throw Object.assign(new Error("Oturum gerekli."),{status:401});const {data,error}=await admin.auth.getUser(a.slice(7).trim());if(error||!data.user)throw Object.assign(new Error("Oturum geçersiz."),{status:401});const {data:p,error:pe}=await admin.from("admin_profiles").select("user_id").eq("user_id",data.user.id).eq("active",true).maybeSingle();if(pe)throw Object.assign(new Error("Yönetici doğrulaması başarısız."),{status:503});if(!p)throw Object.assign(new Error("Yönetici yetkisi gerekli."),{status:403});return data.user}
const text=(v:unknown,n:number)=>typeof v==="string"?v.trim().slice(0,n):"";const role=(v:unknown)=>{const r=text(v,32).toLowerCase();return ["crew","tech","warehouse","lead"].includes(r)?r:"crew"};const password=(v:unknown)=>{const p=typeof v==="string"?v:"";if(p.length<10||p.length>128||!/[A-Za-zğüşıöçĞÜŞİÖÇ]/.test(p)||!/\d/.test(p))throw new Error("Şifre en az 10 karakter, bir harf ve bir rakam içermeli.");return p};const usernameOk=(v:string)=>/^[a-z0-9._-]{3,64}$/.test(v);
async function logActivity(actor:string,action:string,id:string,metadata:Record<string,unknown>={}){try{await admin.from("activity_logs").insert({actor_id:actor,action,entity_type:"staff",entity_id:id,metadata})}catch(_){} }
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:headers(req)});if(req.method!=="POST")return out(req,{error:"Method Not Allowed"},405);try{const actor=await requireAdmin(req);const b=await req.json().catch(()=>({}));const action=text(b.action,40);
if(action==="catalog"){const {data,error}=await admin.from("permission_catalog").select("key,category,label,description,sort_order,active").eq("active",true).order("sort_order").order("key");if(error)throw error;return out(req,{permissions:data||[]})}
if(action==="list"){const {data:staff,error}=await admin.from("staff_profiles").select("user_id,username,display_name,role,phone,active,notes,created_at,updated_at").neq("role","admin").order("display_name");if(error)throw error;const ids=(staff||[]).map(s=>s.user_id);const {data:perms,error:pe}=ids.length?await admin.from("staff_permissions").select("user_id,permission_key,enabled").in("user_id",ids):{data:[],error:null};if(pe)throw pe;const map=new Map<string,Record<string,boolean>>();for(const r of perms||[]){if(!map.has(r.user_id))map.set(r.user_id,{});map.get(r.user_id)![r.permission_key]=!!r.enabled}return out(req,{staff:(staff||[]).map(s=>({...s,permissions:map.get(s.user_id)||{}}))})}
const userId=text(b.user_id,64);if(action!=="create"&&!userId)throw new Error("user_id gerekli.");
if(action==="create"){const u=text(b.username,64).toLowerCase(),d=text(b.display_name,120),pw=password(b.password),r=role(b.role),phone=text(b.phone,40)||null;if(!usernameOk(u)||!d)throw new Error("Geçerli kullanıcı adı ve ad soyad gerekli.");const {data:exists,error:xe}=await admin.from("staff_profiles").select("user_id").eq("username",u).maybeSingle();if(xe)throw xe;if(exists)throw new Error("Bu kullanıcı adı zaten kullanılıyor.");const email=`${u}@staff.stagepulse.com.tr`;const {data:created,error:ce}=await admin.auth.admin.createUser({email,password:pw,email_confirm:true,user_metadata:{username:u,display_name:d,role:r}});if(ce||!created.user)throw ce||new Error("Auth hesabı oluşturulamadı.");try{const {data:profile,error:pe}=await admin.from("staff_profiles").insert({user_id:created.user.id,username:u,display_name:d,role:r,phone,active:true}).select("user_id,username,display_name,role,phone,active,notes,created_at,updated_at").single();if(pe)throw pe;const {data:catalog,error:ce2}=await admin.from("permission_catalog").select("key").eq("active",true);if(ce2)throw ce2;const reqPerm=b.permissions&&typeof b.permissions==="object"?b.permissions:{};const rows=(catalog||[]).map(p=>({user_id:created.user.id,permission_key:p.key,enabled:reqPerm[p.key]===true}));if(rows.length){const ins=await admin.from("staff_permissions").insert(rows);if(ins.error)throw ins.error}await logActivity(actor.id,"staff_created",created.user.id,{username:u});return out(req,{ok:true,staff:profile})}catch(e){try{await admin.auth.admin.deleteUser(created.user.id)}catch(_){}throw e}}
const {data:target,error:te}=await admin.from("staff_profiles").select("user_id,username,role,active").eq("user_id",userId).maybeSingle();if(te||!target||target.role==="admin")throw new Error("Personel hesabı bulunamadı.");
if(action==="update"){const patch:Record<string,unknown>={updated_at:new Date().toISOString()};if(b.display_name!=null)patch.display_name=text(b.display_name,120);if(b.role!=null)patch.role=role(b.role);if(b.phone!=null)patch.phone=text(b.phone,40)||null;if(b.notes!=null)patch.notes=text(b.notes,2000)||null;const {data,error}=await admin.from("staff_profiles").update(patch).eq("user_id",userId).select("user_id,username,display_name,role,phone,active,notes,created_at,updated_at").single();if(error)throw error;if(b.password!=null&&String(b.password).length){const {error:pe}=await admin.auth.admin.updateUserById(userId,{password:password(b.password)});if(pe)throw pe;try{await admin.auth.admin.signOut(userId)}catch(_){}}await logActivity(actor.id,"staff_updated",userId);return out(req,{ok:true,staff:data})}
if(action==="set_active"){const active=b.active===true;const {error}=await admin.from("staff_profiles").update({active,updated_at:new Date().toISOString()}).eq("user_id",userId);if(error)throw error;if(!active)try{await admin.auth.admin.signOut(userId)}catch(_){}await logActivity(actor.id,active?"staff_activated":"staff_deactivated",userId);return out(req,{ok:true,active})}
if(action==="permissions"){const raw=b.permissions;if(!raw||typeof raw!=="object")throw new Error("permissions nesnesi gerekli.");const {data:catalog,error:ce}=await admin.from("permission_catalog").select("key").eq("active",true);if(ce)throw ce;const del=await admin.from("staff_permissions").delete().eq("user_id",userId);if(del.error)throw del.error;const rows=(catalog||[]).map(p=>({user_id:userId,permission_key:p.key,enabled:raw[p.key]===true,updated_at:new Date().toISOString()}));if(rows.length){const ins=await admin.from("staff_permissions").insert(rows);if(ins.error)throw ins.error}await logActivity(actor.id,"staff_permissions_updated",userId,{permission_count:rows.filter(x=>x.enabled).length});return out(req,{ok:true,enabled_count:rows.filter(x=>x.enabled).length})}
if(action==="reset_password"){const {error}=await admin.auth.admin.updateUserById(userId,{password:password(b.password)});if(error)throw error;try{await admin.auth.admin.signOut(userId)}catch(_){}await logActivity(actor.id,"staff_password_reset",userId);return out(req,{ok:true})}
if(action==="delete"){const pe=await admin.from("staff_permissions").delete().eq("user_id",userId);if(pe.error)throw pe.error;const sp=await admin.from("staff_profiles").delete().eq("user_id",userId);if(sp.error)throw sp.error;const {error}=await admin.auth.admin.deleteUser(userId);if(error)throw error;return out(req,{ok:true,deleted_user_id:userId})}
throw new Error("Geçersiz işlem.");}catch(e){const status=e&&typeof e==="object"&&"status"in e&&typeof e.status==="number"?e.status:400;return out(req,{error:e instanceof Error?e.message:"İşlem başarısız."},status)}});