/* Stagepulse portal — realtime data + notification sync. */
(() => {
  if (!window.supabase) return;
  const client=window.supabase.createClient('https://mtjcqqrogjqaxkagwkti.supabase.co','sb_publishable_yR_HlWlFbYYq22tQmiB9LA_acq6bQi6');let channel=null,refreshTimer=null,refreshPending=false;
  const currentView=()=> (location.hash||'#home').slice(1)||'home';const activeEditor=()=>{const el=document.activeElement;return !!el&&/^(INPUT|TEXTAREA|SELECT)$/.test(el.tagName);};
  const refresh=()=>{refreshTimer=null;const v=currentView();const btn=document.querySelector(`#sideNav button[data-view="${CSS.escape(v)}"]`);if(activeEditor()){refreshPending=true;if(typeof window.toast==='function')window.toast('Yeni değişiklik geldi. Açık formu kaydettikten sonra ekran yenilenecek.',true);return;}refreshPending=false;if(btn)btn.click();};
  const scheduleRefresh=()=>{if(refreshTimer)clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,450);};const notifyLocal=p=>{const n=p?.new||{};if(n.title&&typeof window.toast==='function')window.toast(`${n.title}: ${n.body||''}`.trim(),true);if(currentView()==='notifications')scheduleRefresh();};
  async function start(){try{const {data}=await client.auth.getUser();const uid=data?.user?.id;if(!uid)return;if(channel)await client.removeChannel(channel);channel=client.channel(`stagepulse-portal-live-${uid}`).on('postgres_changes',{event:'*',schema:'public',table:'teklifler'},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'jobs'},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'equipment'},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'customers'},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'settlements'},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'payments'},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'services'},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'price_rules'},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'service_equipment_defaults'},scheduleRefresh).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`recipient_user_id=eq.${uid}`},notifyLocal).subscribe();}catch(e){console.warn('Stagepulse realtime portal sync failed:',e);}}
  window.addEventListener('load',()=>setTimeout(start,1200));document.addEventListener('visibilitychange',()=>{if(!document.hidden)start();});document.addEventListener('blur',()=>{if(refreshPending&&!activeEditor())scheduleRefresh();},true);
})();
