/* Stagepulse Personel Portal v121 — mobile shell + permission/view integrity hotfix. */
(() => {
 'use strict';
 const NAV=[
  ['SATIŞ',[['home','Genel Bakış','dashboard.view'],['offers','Teklifler','offers.view'],['customers','Müşteriler','customers.view'],['finance','Ödemeler / Finans','payments.view'],['pricing','Fiyatlandırma','pricing.view']]],
  ['OPERASYON',[['jobs','İşler','schedule.view'],['equipment','Ekipman','equipment.view'],['analytics','Analitik','analytics.view'],['activity','Aktivite','activity.view'],['notifications','Bildirimler','notifications.view']]],
  ['SİSTEM',[['settings','Ayarlar','settings.view']]]
 ];
 const has=perm=>{try{return typeof window.can==='function'&&window.can(perm)===true}catch(_){return false}};
 function closeMenu(){const side=document.getElementById('sidebar'),overlay=document.getElementById('mobileOverlay');side?.classList.remove('open');if(overlay){overlay.hidden=true;overlay.classList.remove('open')}document.body.classList.remove('portal-menu-open');document.getElementById('menuBtn')?.setAttribute('aria-expanded','false')}
 function openMenu(){const side=document.getElementById('sidebar'),overlay=document.getElementById('mobileOverlay');if(!side)return;side.classList.add('open');if(overlay){overlay.hidden=false;overlay.classList.add('open')}document.body.classList.add('portal-menu-open');document.getElementById('menuBtn')?.setAttribute('aria-expanded','true')}
 function rebuildNav(){const nav=document.getElementById('sideNav');if(!nav||typeof window.loadView!=='function')return;const badge=document.getElementById('portalPermissionBadge');nav.querySelectorAll('button[data-view],.portal-nav-label').forEach(el=>el.remove());const fragment=document.createDocumentFragment();let visibleCount=0;for(const[group,items]of NAV){const allowed=items.filter(([, ,perm])=>has(perm));if(!allowed.length)continue;const label=document.createElement('div');label.className='portal-nav-label';label.textContent=group;fragment.appendChild(label);for(const[view,text]of allowed){const button=document.createElement('button');button.type='button';button.dataset.view=view;button.textContent=text;button.setAttribute('aria-label',text);button.onclick=e=>{e.preventDefault();e.stopPropagation();closeMenu();window.loadView(view)};fragment.appendChild(button);visibleCount++}}if(badge)fragment.appendChild(badge);nav.replaceChildren(fragment);nav.dataset.v121='1';document.documentElement.dataset.portalPermissionCount=String(visibleCount)}
 function bindMenu(){let menu=document.getElementById('menuBtn'),overlay=document.getElementById('mobileOverlay');if(!menu)return;if(!menu.dataset.v121){const fresh=menu.cloneNode(true);fresh.dataset.v121='1';menu.replaceWith(fresh)}const current=document.getElementById('menuBtn');if(current&&!current.dataset.v121Bound){current.dataset.v121Bound='1';current.type='button';current.setAttribute('aria-controls','sidebar');current.setAttribute('aria-expanded','false');current.onclick=e=>{e.preventDefault();e.stopPropagation();document.getElementById('sidebar')?.classList.contains('open')?closeMenu():openMenu()}}if(overlay&&!overlay.dataset.v121Bound){overlay.dataset.v121Bound='1';overlay.onclick=e=>{if(e.target===overlay)closeMenu()}}document.querySelectorAll('#sideNav button[data-view]').forEach(button=>button.addEventListener('click',closeMenu,{passive:true}))}
 function repairTitles(){const titles={home:['Genel Bakış','Özet'],jobs:['İşler','Takvim ve operasyon'],equipment:['Ekipman','Envanter'],offers:['Teklifler','Satış talepleri'],customers:['Müşteriler','Müşteri kayıtları'],finance:['Ödemeler / Finans','Finans'],pricing:['Fiyatlandırma','Hizmet taban fiyatları'],analytics:['Analitik','Raporlar'],activity:['Aktivite','Sistem hareketleri'],notifications:['Bildirimler','Bildirim merkezi'],settings:['Ayarlar','Hesap ve sistem']};const view=(location.hash||'#home').slice(1)||'home',pair=titles[view]||titles.home;const h=document.getElementById('portalViewTitle'),s=document.getElementById('portalViewSubtitle');if(h)h.textContent=pair[0];if(s)s.textContent=pair[1]}
 function install(){document.getElementById('sidebar')?.classList.add('admin-visual-menu');bindMenu();rebuildNav();repairTitles();window.dispatchEvent(new CustomEvent('stagepulse:v121-ready'))}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
 window.addEventListener('stagepulse:permissions-ready',install);window.addEventListener('hashchange',repairTitles);window.StagepulsePersonnelV121={install,openMenu,closeMenu,rebuildNav};
})();
