/* Stagepulse Personel — canonical RBAC and real write actions */
(() => {
  const oldAfterLogin = window.afterLogin;
  const aliases = {accept_job:'jobs.accept',reject_job:'jobs.reject',update_job_status:'jobs.status.update',update_job_notes:'jobs.notes.update',manage_job_equipment:'jobs.equipment.manage',pricing_manage:'pricing.manage',equipment_manage:'equipment.manage',customers_manage:'customers.manage',offers_manage:'offers.manage',offer_create:'offers.create',offer_update:'offers.update',offer_send:'offers.send'};
  function hydrate(){
    const p=window.staffUser;
    if(!p||typeof p!=='object')return;
    p.permissions=p.permissions&&typeof p.permissions==='object'?p.permissions:{};
    Object.entries(aliases).forEach(([legacy,canonical])=>{if(p.permissions[canonical]===true)p.permissions[legacy]=true;});
  }
  window.afterLogin=function(){const r=oldAfterLogin?.apply(this,arguments);hydrate();return r;};
  hydrate();
  const esc=s=>String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const can=k=>typeof window.can==='function'?window.can(k):window.staffUser?.permissions?.[k]===true;
  const notify=m=>typeof window.toast==='function'?window.toast(m,false):alert(m);
  const input=(id,label,type='text',value='')=>`<label>${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`;
  const panel=(title,fields,button)=>`<div class="panel staff-crud-panel"><div class="panel-head"><h3>${title}</h3></div><form class="staff-crud-form">${fields.join('')}<button class="btn btn-primary" type="submit">${button}</button></form></div>`;
  const mount=html=>{const c=document.querySelector('#content');if(!c)return null;const x=document.createElement('div');x.innerHTML=html;x.dataset.staffCrud='1';c.prepend(x);return x;};
  async function loadOfferRows(){
    if(!can('offers.view')&&!can('offers.manage')&&!can('offers.update')&&!can('offers.send'))return [];
    const {data,error}=await sb.from('offers_staff').select('id,quote_number,name,company,location,people,event_date,event_type,type,agreed_amount,currency,status,created_at').order('event_date',{ascending:true,nullsFirst:false});
    if(error){notify(error.message);return [];} return data||[];
  }
  async function offerActions(){
    const rows=await loadOfferRows();
    if(can('offers.create')||can('offers.manage')){const box=mount(panel('Yeni teklif oluştur',[input('spOfferName','Müşteri adı'),input('spOfferCompany','Firma'),input('spOfferPhone','Telefon'),input('spOfferEmail','E-posta','email'),input('spOfferLocation','Lokasyon'),input('spOfferPeople','Kişi sayısı','number'),input('spOfferDate','Etkinlik tarihi','date'),input('spOfferTotal','Toplam fiyat','number'),input('spOfferMessage','Not')],'Teklifi oluştur'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();if(!can('offers.create')&&!can('offers.manage'))return notify('Teklif oluşturma yetkiniz yok.');const {error}=await sb.rpc('staff_create_offer',{p_name:$('#spOfferName').value.trim(),p_company:$('#spOfferCompany').value.trim()||null,p_phone:$('#spOfferPhone').value.trim()||null,p_email:$('#spOfferEmail').value.trim()||null,p_location:$('#spOfferLocation').value.trim()||null,p_people:Number($('#spOfferPeople').value)||null,p_message:$('#spOfferMessage').value.trim()||null,p_total:Number($('#spOfferTotal').value)||0,p_services:[]});if(error)return notify(error.message);window.toast?.('Teklif oluşturuldu.');await window.loadView('offers');});}
    if(can('offers.update')||can('offers.manage')){const box=mount(panel('Teklif düzenle',[`<label>Teklif<select id="spEditOffer">${rows.map(o=>`<option value="${o.id}">${esc(o.quote_number||o.id)} · ${esc(o.name||'')} · ${esc(o.status||'')}</option>`).join('')}</select></label>`,input('spEditName','Müşteri adı'),input('spEditCompany','Firma'),input('spEditLocation','Lokasyon'),input('spEditPeople','Kişi sayısı','number'),input('spEditDate','Etkinlik tarihi','date'),input('spEditTotal','Toplam','number'),input('spEditMessage','Not')],'Teklifi kaydet'));const select=box?.querySelector('#spEditOffer');const fill=()=>{const o=rows.find(x=>x.id===select?.value);if(!o)return;$('#spEditName').value=o.name||'';$('#spEditCompany').value=o.company||'';$('#spEditLocation').value=o.location||'';$('#spEditPeople').value=o.people??'';$('#spEditDate').value=o.event_date||'';$('#spEditTotal').value=o.agreed_amount??0;$('#spEditMessage').value='';};select?.addEventListener('change',fill);fill();const submit=box?.querySelector('form');if(submit)submit.addEventListener('submit',async e=>{e.preventDefault();if(!can('offers.update')&&!can('offers.manage'))return notify('Teklif düzenleme yetkiniz yok.');const id=select?.value;if(!id)return notify('Düzenlenecek teklif seçilmedi.');const {error}=await sb.rpc('staff_update_offer',{p_id:id,p_name:$('#spEditName').value.trim(),p_company:$('#spEditCompany').value.trim()||null,p_location:$('#spEditLocation').value.trim()||null,p_people:Number($('#spEditPeople').value)||null,p_event_date:$('#spEditDate').value||null,p_message:$('#spEditMessage').value.trim()||null,p_total:Number($('#spEditTotal').value)||0,p_services:[]});if(error)return notify(error.message);window.toast?.('Teklif güncellendi.');await window.loadView('offers');});}
    if(can('offers.send')||can('offers.manage')){const box=mount(panel('Teklif gönder',[`<label>Teklif<select id="spSendOffer">${rows.map(o=>`<option value="${o.id}">${esc(o.quote_number||o.id)} · ${esc(o.name||'')} · ${esc(o.status||'')}</option>`).join('')}</select></label>`],'Gönder'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();if(!can('offers.send')&&!can('offers.manage'))return notify('Teklif gönderme yetkiniz yok.');const id=$('#spSendOffer')?.value;if(!id)return notify('Gönderilecek teklif seçilmedi.');const {error}=await sb.rpc('staff_send_offer',{p_id:id});if(error)return notify(error.message);window.toast?.('Teklif gönderildi.');await window.loadView('offers');});}
    if(!rows.length&&(can('offers.update')||can('offers.send')||can('offers.manage'))){const c=document.querySelector('#content');if(c){const n=document.createElement('p');n.className='muted staff-crud-empty';n.textContent='İşlem yapılabilecek teklif bulunamadı.';c.prepend(n);}}
  }
  async function customerActions(){if(!can('customers.create')&&!can('customers.manage'))return;const box=mount(panel('Yeni müşteri',[input('spCustomerName','Ad / müşteri'),input('spCustomerCompany','Firma'),input('spCustomerPhone','Telefon'),input('spCustomerEmail','E-posta','email'),input('spCustomerNotes','Not')],'Müşteri ekle'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();if(!can('customers.create')&&!can('customers.manage'))return notify('Müşteri oluşturma yetkiniz yok.');const {error}=await sb.rpc('staff_create_customer',{p_name:$('#spCustomerName').value.trim(),p_company:$('#spCustomerCompany').value.trim()||null,p_phone:$('#spCustomerPhone').value.trim()||null,p_email:$('#spCustomerEmail').value.trim()||null,p_notes:$('#spCustomerNotes').value.trim()||null});if(error)return notify(error.message);window.toast?.('Müşteri eklendi.');await window.loadView('customers');});}
  async function pricingActions(){if(!can('pricing.manage')&&!can('pricing.update'))return;const box=mount(panel('Yeni hizmet / fiyat',[input('spPriceName','Hizmet adı'),input('spPriceDesc','Açıklama'),input('spPriceValue','Fiyat','number'),input('spPriceSort','Sıra','number','0')],'Kaydet'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();if(!can('pricing.manage')&&!can('pricing.update'))return notify('Fiyatlandırma düzenleme yetkiniz yok.');const {error}=await sb.rpc('staff_upsert_service',{p_id:null,p_name:$('#spPriceName').value.trim(),p_description:$('#spPriceDesc').value.trim()||null,p_base_price:Number($('#spPriceValue').value)||0,p_sort_order:Number($('#spPriceSort').value)||0});if(error)return notify(error.message);window.toast?.('Fiyatlandırma kaydedildi.');await window.loadView('pricing');});}
  async function equipmentActions(){if(!can('equipment.manage')&&!can('equipment.create')&&!can('equipment.update'))return;const box=mount(panel('Ekipman ekle',[input('spEqCategory','Kategori'),input('spEqBrand','Marka'),input('spEqModel','Model'),input('spEqQty','Adet','number','1'),input('spEqNotes','Not')],'Ekipmanı kaydet'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();if(!can('equipment.manage')&&!can('equipment.create')&&!can('equipment.update'))return notify('Ekipman düzenleme yetkiniz yok.');const {error}=await sb.rpc('staff_upsert_equipment',{p_id:null,p_category:$('#spEqCategory').value.trim(),p_brand:$('#spEqBrand').value.trim()||null,p_model:$('#spEqModel').value.trim()||null,p_quantity:Number($('#spEqQty').value)||0,p_notes:$('#spEqNotes').value.trim()||null});if(error)return notify(error.message);window.toast?.('Ekipman kaydedildi.');await window.loadView('equipment');});}
  const oldOffers=window.offersView,oldPricing=window.pricingView;
  if(oldOffers)window.offersView=async function(){const r=await oldOffers.apply(this,arguments);await offerActions();return r;};
  if(oldPricing)window.pricingView=async function(){const r=await oldPricing.apply(this,arguments);await pricingActions();return r;};
  window.respondJob=async(id,response)=>{const permission=response==='accepted'?'jobs.accept':'jobs.reject';if(!can(permission)&&!can('jobs.manage'))return notify(response==='accepted'?'İş kabul yetkiniz yok.':'İş reddetme yetkiniz yok.');const {error}=await sb.rpc('staff_respond_job',{p_job_id:id,p_response:response,p_note:null});if(error)return notify(error.message);window.toast?.(response==='accepted'?'İş kabul edildi.':'İş reddedildi.');await window.loadView('jobs');};
  window.setJobStatus=async(id,status)=>{if(!can('jobs.status.update')&&!can('jobs.manage'))return notify('İş durumu değiştirme yetkiniz yok.');const {error}=await sb.rpc('staff_update_job_status',{p_job_id:id,p_status:status});if(error)return notify(error.message);window.toast?.('İş durumu güncellendi.');await window.loadView('jobs');};
  window.updateJobNotes=async(id)=>{if(!can('jobs.notes.update')&&!can('jobs.manage'))return notify('İş notu düzenleme yetkiniz yok.');const note=prompt('İş notu','');if(note===null)return;const {error}=await sb.rpc('staff_update_job_notes',{p_job_id:id,p_notes:note});if(error)return notify(error.message);window.toast?.('İş notu kaydedildi.');await window.loadView('jobs');};
})();