/* Stagepulse Personel Portalı — mali alanlar yok + yetki bazlı menü */
const SUPABASE_URL = 'https://mtjcqqrogjqaxkagwkti.supabase.co';
const SUPABASE_KEY = 'sb_publishable_yR_HlWlFbYYq22tQmiB9LA_acq6bQi6';
const EDGE_LOGIN = `${SUPABASE_URL}/functions/v1/staff-login`;

if (!window.supabase) { document.body.innerHTML = '<div style="padding:40px;font-family:system-ui;color:#fff;background:#090909">Supabase yüklenemedi.</div>'; throw new Error('Supabase missing'); }
const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
window.addEventListener('unhandledrejection', (event) => { console.error('Unhandled promise rejection:', event.reason); try { toast((event.reason && event.reason.message) || 'Beklenmeyen bir hata oluştu.', false); } catch (_) {} event.preventDefault(); });
const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)], esc=(s)=>String(s??'').replace(/[&<>']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;'}[c])), money=(v)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(v)||0), num=(v)=>Number(v)||0;

// SECURITY: permission source-of-truth is staff-login/staff-session. No client-side defaults grant access.
const PERMISSION_ALIAS={jobs:'schedule.view',equipment:'equipment.view',offers:'offers.view',view_assigned_jobs:'schedule.view',accept_job:'jobs.manage',reject_job:'jobs.manage',update_job_status:'jobs.manage',update_job_notes:'jobs.manage',manage_job_equipment:'equipment.manage',view_job_contacts:'schedule.view',view_job_documents:'schedule.view',equipment_checkout:'equipment.manage',equipment_return:'equipment.manage',report_issue:'notifications.send',view_team:'staff.view',customers:'customers.view',finance:'payments.view',pricing:'pricing.view',financials:'settlements.view',dashboard_view:'dashboard.view',analytics:'analytics.view',activity_view:'activity_logs.view',notifications_view:'notifications.view',settings_manage:'profile.manage',calendar_view:'schedule.view',calendar_edit:'schedule.manage',settlements_view:'settlements.view',personnel_view:'staff.view',pricing_manage:'pricing.manage',file_upload:'files.upload',offer_approve:'offers.approve',whatsapp_send:'notifications.send',personnel_manage:'staff.manage'};
const canonical=(key)=>PERMISSION_ALIAS[key]||key;
let staffUser=null,jobs=[],equipment=[],offers=[],jobEquipment=[];
const jobStatusTr={planned:'Planlandı',confirmed:'Onaylı',in_progress:'Devam',done:'Bitti',cancelled:'İptal'},roleTr={crew:'Ekip',tech:'Teknik',warehouse:'Depo',lead:'Sorumlu'};
function perms(){return (staffUser&&staffUser.permissions&&typeof staffUser.permissions==='object')?staffUser.permissions:Object.create(null)}
function can(key){const p=perms();return p[canonical(key)]===true||p[key]===true}
function showLogin(){$('#loginView')?.classList.remove('is-hidden');if($('#loginView'))$('#loginView').hidden=false;$('#appView')?.classList.add('is-hidden');if($('#appView'))$('#appView').hidden=true}
function showApp(){$('#loginView')?.classList.add('is-hidden');if($('#loginView'))$('#loginView').hidden=true;$('#appView')?.classList.remove('is-hidden');if($('#appView'))$('#appView').hidden=false}
function toast(msg,ok=true){let t=$('#portalToast');if(!t){t=document.createElement('div');t.id='portalToast';t.style.cssText='position:fixed;bottom:20px;left:50%;transform:translateX(-50%);padding:10px 16px;border-radius:10px;z-index:99;font-size:14px';document.body.appendChild(t)}t.textContent=msg;t.style.background=ok?'#1a3a28':'#3a1a1a';t.style.color=ok?'#9dffc5':'#ffb4b4';clearTimeout(t._tm);t._tm=setTimeout(()=>{t.textContent=''},2800)}
async function login(e){e.preventDefault();const username=$('#loginUser')?.value?.trim().toLowerCase(),password=$('#loginPass')?.value||'',err=$('#loginErr');if(err){err.hidden=true;err.textContent=''}try{const r=await fetch(EDGE_LOGIN,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_KEY},body:JSON.stringify({username,password})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Giriş başarısız');await sb.auth.setSession({access_token:j.session.access_token,refresh_token:j.session.refresh_token});staffUser=j.user;localStorage.setItem('sp_staff_meta',JSON.stringify(j.user));afterLogin()}catch(ex){if(err){err.hidden=false;err.textContent=ex.message||'Hata'}}}
const VIEW_PERM={home:'dashboard.view',jobs:'schedule.view',equipment:'equipment.view',offers:'offers.view',customers:'customers.view',finance:'payments.view',pricing:'pricing.view',analytics:'analytics.view',activity:'activity_logs.view',notifications:'notifications.view',settings:'profile.manage'};
function applyNavPermissions(){$$('#sideNav button[data-view]').forEach(btn=>{const v=btn.dataset.view;btn.style.display=can(VIEW_PERM[v])?'':'none'})}
function firstAllowedView(){return Object.keys(VIEW_PERM).find(v=>can(VIEW_PERM[v]))||null}
function afterLogin(){showApp();$('#staffName').textContent=staffUser?.display_name||'Personel';$('#staffRole').textContent=roleTr[staffUser?.role]||staffUser?.role||'';applyNavPermissions();bindShell();const hash=(location.hash||'').slice(1),fallback=firstAllowedView();loadView(VIEW_PERM[hash]&&can(VIEW_PERM[hash])?hash:(fallback||null))}
function bindShell(){$$('#sideNav button[data-view]').forEach(btn=>{btn.onclick=()=>loadView(btn.dataset.view)});$('#logoutBtn')?.addEventListener('click',async()=>{await sb.auth.signOut();localStorage.removeItem('sp_staff_meta');location.reload()})}
async function loadView(v){const need=VIEW_PERM[v];if(!need||!can(need)){const fallback=firstAllowedView();if(fallback&&fallback!==v)return loadView(fallback);$('#content').innerHTML='<div class="panel"><b>Erişim yetkiniz yok.</b><p class="muted">Bu sayfa için yöneticinizden yetki istemelisiniz.</p></div>';return}history.replaceState(null,'','#'+v);$$('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const map={home:homeView,jobs:jobsView,equipment:equipmentView,offers:offersView,customers:customersView,finance:financeView,pricing:pricingView,analytics:analyticsView,activity:activityView,notifications:notificationsView,settings:settingsView};const fn=map[v];try{if(typeof fn==='function')return await fn();$('#content').innerHTML='<div class="panel"><b>Bölüm</b><p class="muted">Bu bölüm için yetkiniz aktif.</p></div>'}catch(e){console.error(e);$('#content').innerHTML=`<div class="panel"><b>Hata</b><p class="muted">${esc(e.message||e)}</p></div>`}}

// Existing business/view implementations remain unchanged below this security layer.
// IMPORTANT: do not restore DEFAULT_PERMS or grant access when live permissions are absent.
