/* Stagepulse Portal — canonical RBAC utility modules. */
(() => {
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2}).format(Number(v)||0);
  const date=v=>v?String(v).slice(0,16).replace('T',' '):'—';
  const roleTr={owner:'Patron / Owner',super_admin:'Süper Admin',upper_admin:'Üst Admin',ceo:'CEO',department_manager:'Departman Yöneticisi',regional_manager:'Bölge Sorumlusu',employee:'Çalışan'};
  const has=k=>typeof window.can==='function'&&window.can(k);
  window.notificationsView=async()=>{if(!has('notifications.view'))return toast('Bildirim yetkiniz yok',false);const r=await sb.from('notifications').select('id,kind,title,body,read_at,created_at,offer_id').eq('recipient_user_id',window.staffUser?.id).order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;const rows=r.data||[];$('#content').innerHTML=`<div class="page-head"><div><h1>Bildirimler</h1><p class="muted">Size gönderilen sistem bildirimleri</p></div><button class="btn" ${rows.some(x=>!x.read_at)?'':'disabled'} onclick="window.__spMarkAllNotificationsRead()">Tümünü okundu yap</button></div><div class="panel">${rows.map(n=>`<div class="row-item" style="${n.read_at?'opacity:.6':''}"><div class="row-main"><strong>${esc(n.title)}</strong><span class="muted">${esc(n.body||'')} · ${date(n.created_at)}</span></div><div class="row-side">${!n.read_at?`<button class="btn" onclick="window.__spMarkNotificationRead('${esc(n.id)}')">Okundu</button>`:''}<span class="status">${esc(n.kind||'sistem')}</span></div></div>`).join('')||'<p class="muted">Bildirim yok.</p>'}</div>`};
  window.__spMarkNotificationRead=async id=>{if(!has('notifications.view'))return;const r=await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('recipient_user_id',window.staffUser?.id);if(r.error)return toast(r.error.message,false);await window.notificationsView()};
  window.__spMarkAllNotificationsRead=async()=>{if(!has('notifications.view'))return;const r=await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('recipient_user_id',window.staffUser?.id).is('read_at',null);if(r.error)return toast(r.error.message,false);toast('Bildirimler okundu.');await window.notificationsView()};
  window.activityView=async()=>{if(!has('activity.view'))return toast('Aktivite yetkiniz yok',false);const r=await sb.from('activity_logs').select('id,action,entity_type,metadata,created_at').order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;$('#content').innerHTML=`<div class="page-head"><div><h1>Aktivite</h1><p class="muted">Sistem işlem geçmişi</p></div></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Tarih</th><th>İşlem</th><th>Tür</th><th>Detay</th></tr></thead><tbody>${(r.data||[]).map(x=>`<tr><td>${date(x.created_at)}</td><td>${esc(x.action)}</td><td>${esc(x.entity_type||'—')}</td><td><code>${esc(JSON.stringify(x.metadata||{}).slice(0,180))}</code></td></tr>`).join('')||'<tr><td colspan="4" class="muted">Kayıt yok.</td></tr>'}</tbody></table></div></div>`};
  window.analyticsView=async()=>{if(!has('analytics.view'))return toast('Analitik yetkiniz yok',false);const offersRes=has('offers.view')?await sb.from('teklifler').select('id,status,created_at,total').limit(1000):{data:[],error:null},jobsRes=(has('jobs.view')||has('schedule.view'))?await sb.from('jobs').select('id,status,event_at').limit(1000):{data:[],error:null};if(offersRes.error||jobsRes.error)throw offersRes.error||jobsRes.error;const offers=offersRes.data||[],jobs=jobsRes.data||[],accepted=offers.filter(x=>x.status==='accepted').length,activeJobs=jobs.filter(x=>!['done','cancelled'].includes(x.status)).length,rate=offers.length?Math.round(accepted/offers.length*100):0;$('#content').innerHTML=`<div class="page-head"><div><h1>Analitik</h1><p class="muted">Yetkili olduğunuz operasyon verileri</p></div></div><div class="cards"><div class="card"><span class="card-label">Teklif</span><div class="metric">${offers.length}</div></div><div class="card"><span class="card-label">Kabul</span><div class="metric">${accepted}</div></div><div class="card"><span class="card-label">Dönüşüm</span><div class="metric">${rate}%</div></div><div class="card"><span class="card-label">Aktif iş</span><div class="metric">${activeJobs}</div></div></div>`};
  window.settingsView=async()=>{if(!has('settings.view'))return toast('Ayarlar yetkiniz yok',false);const r=await sb.from('org_memberships').select('role:role_id(code,name),position:position_id(code,name),department:department_id(name),region:region_id(name)').eq('user_id',window.staffUser?.id).maybeSingle();if(r.error)throw r.error;const p=(await sb.from('staff_notification_preferences').select('enabled,offers,jobs,schedule,system').eq('user_id',window.staffUser?.id).maybeSingle()).data||{enabled:true,offers:true,jobs:true,schedule:true,system:true},m=r.data;$('#content').innerHTML=`<div class="page-head"><div><h1>Ayarlar</h1><p class="muted">Organizasyon ve bildirim tercihleri</p></div></div><div class="grid2"><div class="panel"><h3>Organizasyon</h3><label>Rol<input value="${esc(roleTr[m?.role?.code]||m?.role?.name||window.staffUser?.role||'')}" disabled></label><label>Pozisyon<input value="${esc(m?.position?.name||'')}" disabled></label><label>Departman<input value="${esc(m?.department?.name||'')}" disabled></label><label>Bölge<input value="${esc(m?.region?.name||'')}" disabled></label></div><div class="panel"><h3>Bildirim tercihleri</h3><label><input id="spPrefMaster" type="checkbox" ${p.enabled?'checked':''}> Bildirimleri açık tut</label><label><input id="spPrefOffers" type="checkbox" ${p.offers?'checked':''}> Teklif bildirimleri</label><label><input id="spPrefJobs" type="checkbox" ${p.jobs?'checked':''}> İş bildirimleri</label><label><input id="spPrefSchedule" type="checkbox" ${p.schedule?'checked':''}> Takvim bildirimleri</label><label><input id="spPrefSystem" type="checkbox" ${p.system?'checked':''}> Sistem bildirimleri</label><button class="btn btn-primary" onclick="window.__spSaveNotificationPrefs()">Tercihleri kaydet</button></div></div>`};
  window.__spSaveNotificationPrefs=async()=>{if(!has('settings.view'))return toast('Ayarlar yetkiniz yok',false);const r=await sb.rpc('staff_update_notification_preferences',{p_master:$('#spPrefMaster').checked,p_offers:$('#spPrefOffers').checked,p_jobs:$('#spPrefJobs').checked,p_schedule:$('#spPrefSchedule').checked,p_system:$('#spPrefSystem').checked});if(r.error)return toast(r.error.message,false);toast('Bildirim tercihleri kaydedildi.')};
  window.financeView=async()=>{if(!has('payments.view'))return toast('Ödemeler yetkiniz yok',false);const r=await sb.from('payments').select('id,offer_id,description,amount,due_date,paid_at,status,created_at').order('due_date',{ascending:true,nullsFirst:false});if(r.error)throw r.error;const rows=r.data||[],sum=a=>a.reduce((s,x)=>s+Number(x.amount||0),0),pending=sum(rows.filter(x=>['pending','deposit','partial','overdue'].includes(x.status))),paid=sum(rows.filter(x=>x.status==='paid')),overdue=sum(rows.filter(x=>x.status==='overdue')),st={pending:'Bekliyor',deposit:'Kapora',partial:'Kısmi',paid:'Ödendi',overdue:'Gecikmiş'};$('#content').innerHTML=`<div class="page-head"><div><h1>Ödemeler / Finans</h1><p class="muted">Yetkili olduğunuz tahsilat kayıtları</p></div></div><div class="cards"><div class="card"><span class="card-label">Bekleyen</span><div class="metric">${money(pending)}</div></div><div class="card"><span class="card-label">Tahsil edilen</span><div class="metric">${money(paid)}</div></div><div class="card"><span class="card-label">Gecikmiş</span><div class="metric">${money(overdue)}</div></div><div class="card"><span class="card-label">Kayıt</span><div class="metric">${rows.length}</div></div></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Açıklama</th><th>Tutar</th><th>Vade</th><th>Ödeme</th><th>Durum</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.description||'—')}</td><td><b>${money(x.amount)}</b></td><td>${esc(x.due_date||'—')}</td><td>${esc((x.paid_at||'').slice(0,10)||'—')}</td><td><span class="status">${esc(st[x.status]||x.status||'—')}</span></td></tr>`).join('')||'<tr><td colspan="5" class="muted">Ödeme kaydı yok</td></tr>'}</tbody></table></div></div>`};
})();