/* Stagepulse Personel — canonical RBAC + CRUD/write actions. */
(() => {
  'use strict';
  const q=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const can=k=>typeof window.can==='function'?window.can(k):window.staffUser?.permissions?.[k]===true;
  const notify=(m,ok=false)=>typeof window.toast==='function'?window.toast(m,ok):(!ok&&console.error(m));
  const ok=m=>notify(m,true);
  const aliases={accept_job:'jobs.accept',reject_job:'jobs.reject',update_job_status:'jobs.status.update',update_job_notes:'jobs.notes.update',manage_job_equipment:'jobs.equipment.manage',pricing_manage:'pricing.manage',equipment_manage:'equipment.manage',customers_manage:'customers.manage',offers_manage:'offers.manage',offer_create:'offers.create',offer_update:'offers.update',offer_send:'offers.send'};
  function hydrate(){const p=window.staffUser;if(!p||typeof p!=='object')return;p.permissions=p.permissions&&typeof p.permissions==='object'?p.permissions:{};Object.entries(aliases).forEach(([legacy,canonical])=>{if(p.permissions[canonical]===true)p.permissions[legacy]=true;});}
  const oldAfterLogin=window.afterLogin;window.afterLogin=function(){const r=oldAfterLogin?.apply(this,arguments);hydrate();return r};hydrate();
  const input=(id,label,type='text',value='')=>`<label>${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`;
  const panel=(title,fields,button)=>`<div class="panel staff-crud-panel"><div class="panel-head"><h3>${title}</h3></div><form class="staff-crud-form">${fields.join('')}<button class="btn btn-primary" type="submit">${button}</button></form></div>`;
  const mount=html=>{const c=q('#content');if(!c)return null;const x=document.createElement('div');x.innerHTML=html;x.dataset.staffCrud='1';c.prepend(x);return x};
  async function loadOfferRows(){if(!can('offers.view')&&!can('offers.manage')&&!can('offers.update')&&!can('offers.send')&&!can('offers.delete'))return[];const {data,error}=await sb.from('offers_staff').select('id,quote_number,name,company,location,people,event_date,event_type,type,agreed_amount,currency,status,created_at').order('event_date',{ascending:true,nullsFirst:false});if(error){notify(error.message);return[]}return data||[]}
  async function offerActions(){const list=await loadOfferRows();if(can('offers.create')||can('offers.manage')){const box=mount(panel('Yeni teklif oluştur',[input('spOfferName','Müşteri adı'),input('spOfferCompany','Firma'),input('spOfferPhone','Telefon'),input('spOfferEmail','E-posta','email'),input('spOfferLocation','Lokasyon'),input('spOfferPeople','Kişi sayısı','number'),input('spOfferDate','Etkinlik tarihi','date'),input('spOfferTotal','Toplam fiyat','number'),input('spOfferMessage','Not')],'Teklifi oluştur'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();if(!can('offers.create')&&!can('offers.manage'))return notify('Teklif oluşturma yetkiniz yok.');const {error}=await sb.rpc('staff_create_offer',{p_name:q('#spOfferName')?.value.trim(),p_company:q('#spOfferCompany')?.value.trim()||null,p_phone:q('#spOfferPhone')?.value.trim()||null,p_email:q('#spOfferEmail')?.value.trim()||null,p_location:q('#spOfferLocation')?.value.trim()||null,p_people:Number(q('#spOfferPeople')?.value)||null,p_message:q('#spOfferMessage')?.value.trim()||null,p_total:Number(q('#spOfferTotal')?.value)||0,p_services:[]});if(error)return notify(error.message);ok('Teklif oluşturuldu.');await window.loadView('offers')})}
    if(can('offers.update')||can('offers.manage')){const box=mount(panel('Teklif düzenle',[`<label>Teklif<select id="spEditOffer">${list.map(o=>`<option value="${o.id}">${esc(o.quote_number||o.id)} · ${esc(o.name||'')} · ${esc(o.status||'')}</option>`).join('')}</select></label>`,input('spEditName','Müşteri adı'),input('spEditCompany','Firma'),input('spEditLocation','Lokasyon'),input('spEditPeople','Kişi sayısı','number'),input('spEditDate','Etkinlik tarihi','date'),input('spEditTotal','Toplam','number'),input('spEditMessage','Not')],'Teklifi kaydet'));const sel=box?.querySelector('#spEditOffer');const fill=()=>{const o=list.find(x=>x.id===sel?.value);if(!o)return;q('#spEditName').value=o.name||'';q('#spEditCompany').value=o.company||'';q('#spEditLocation').value=o.location||'';q('#spEditPeople').value=o.people??'';q('#spEditDate').value=o.event_date||'';q('#spEditTotal').value=o.agreed_amount??0;q('#spEditMessage').value=''};sel?.addEventListener('change',fill);fill();box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const id=sel?.value;if(!id)return notify('Düzenlenecek teklif seçilmedi.');const {error}=await sb.rpc('staff_update_offer',{p_id:id,p_name:q('#spEditName')?.value.trim(),p_company:q('#spEditCompany')?.value.trim()||null,p_location:q('#spEditLocation')?.value.trim()||null,p_people:Number(q('#spEditPeople')?.value)||null,p_event_date:q('#spEditDate')?.value||null,p_message:q('#spEditMessage')?.value.trim()||null,p_total:Number(q('#spEditTotal')?.value)||0,p_services:[]});if(error)return notify(error.message);ok('Teklif güncellendi.');await window.loadView('offers')})}
    if(can('offers.send')||can('offers.manage')){const box=mount(panel('Teklif gönder',[`<label>Teklif<select id="spSendOffer">${list.map(o=>`<option value="${o.id}">${esc(o.quote_number||o.id)} · ${esc(o.name||'')} · ${esc(o.status||'')}</option>`).join('')}</select></label>`],'Gönder'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const id=q('#spSendOffer')?.value;if(!id)return notify('Gönderilecek teklif seçilmedi.');const {error}=await sb.rpc('staff_send_offer',{p_id:id});if(error)return notify(error.message);ok('Teklif gönderildi.');await window.loadView('offers')})}
    if(can('offers.delete')){const box=mount(panel('Teklif arşivle',[`<label>Teklif<select id="spODel">${list.map(o=>`<option value="${o.id}">${esc(o.quote_number||o.id)} · ${esc(o.name||'')} · ${esc(o.status||'')}</option>`).join('')}</select></label>`],'Arşivle'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();if(!confirm('Seçilen teklif arşivlensin mi?'))return;const {error}=await sb.rpc('staff_delete_offer',{p_id:q('#spODel')?.value});if(error)return notify(error.message);ok('Teklif arşivlendi.');await window.loadView('offers')})}
  }
  async function customerActions(){if(!can('customers.create')&&!can('customers.manage'))return;const box=mount(panel('Yeni müşteri',[input('spCustomerName','Ad / müşteri'),input('spCustomerCompany','Firma'),input('spCustomerPhone','Telefon'),input('spCustomerEmail','E-posta','email'),input('spCustomerNotes','Not')],'Müşteri ekle'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.rpc('staff_create_customer',{p_name:q('#spCustomerName')?.value.trim(),p_company:q('#spCustomerCompany')?.value.trim()||null,p_phone:q('#spCustomerPhone')?.value.trim()||null,p_email:q('#spCustomerEmail')?.value.trim()||null,p_notes:q('#spCustomerNotes')?.value.trim()||null});if(error)return notify(error.message);ok('Müşteri eklendi.');await window.loadView('customers')})}
  async function customerDelete(){if(!can('customers.delete'))return;const {data,error}=await sb.from('customers_staff').select('id,name,company').order('created_at',{ascending:false});if(error)return notify(error.message);const box=mount(panel('Müşteri arşivle',[`<label>Müşteri<select id="spCDel">${(data||[]).map(x=>`<option value="${x.id}">${esc(x.name||'')}${x.company?' · '+esc(x.company):''}</option>`).join('')}</select></label>`],'Arşivle'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();if(!confirm('Seçilen müşteri arşivlensin mi?'))return;const {error}=await sb.rpc('staff_delete_customer',{p_id:q('#spCDel')?.value});if(error)return notify(error.message);ok('Müşteri arşivlendi.');await window.loadView('customers')})}
  async function equipmentActions(){if(!can('equipment.manage')&&!can('equipment.create')&&!can('equipment.update'))return;const box=mount(panel('Ekipman ekle',[input('spEqCategory','Kategori'),input('spEqBrand','Marka'),input('spEqModel','Model'),input('spEqQty','Adet','number','1'),input('spEqNotes','Not')],'Ekipmanı kaydet'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.rpc('staff_upsert_equipment',{p_id:null,p_category:q('#spEqCategory')?.value.trim(),p_brand:q('#spEqBrand')?.value.trim()||null,p_model:q('#spEqModel')?.value.trim()||null,p_quantity:Number(q('#spEqQty')?.value)||0,p_notes:q('#spEqNotes')?.value.trim()||null});if(error)return notify(error.message);ok('Ekipman kaydedildi.');await window.loadView('equipment')})}
  async function equipmentDelete(){if(!can('equipment.delete'))return;const {data,error}=await sb.from('equipment_staff').select('id,category,brand,model').order('category');if(error)return notify(error.message);const box=mount(panel('Ekipman arşivle',[`<label>Ekipman<select id="spEDel">${(data||[]).map(x=>`<option value="${x.id}">${esc(x.category||'')} · ${esc(x.brand||'')} ${esc(x.model||'')}</option>`).join('')}</select></label>`],'Arşivle'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();if(!confirm('Seçilen ekipman pasifleştirilsin mi?'))return;const {error}=await sb.rpc('staff_delete_equipment',{p_id:q('#spEDel')?.value});if(error)return notify(error.message);ok('Ekipman arşivlendi.');await window.loadView('equipment')})}
  const oldOffers=window.offersView,oldPricing=window.pricingView,oldCustomers=window.customersView,oldEquipment=window.equipmentView;
  if(oldOffers)window.offersView=async function(){const r=await oldOffers.apply(this,arguments);await offerActions();return r};
  if(oldPricing)window.pricingView=async function(){const r=await oldPricing.apply(this,arguments);if(can('pricing.manage')||can('pricing.update')){const box=mount(panel('Yeni hizmet / fiyat',[input('spPriceName','Hizmet adı'),input('spPriceDesc','Açıklama'),input('spPriceValue','Fiyat','number'),input('spPriceSort','Sıra','number','0')],'Kaydet'));box?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.rpc('staff_upsert_service',{p_id:null,p_name:q('#spPriceName')?.value.trim(),p_description:q('#spPriceDesc')?.value.trim()||null,p_base_price:Number(q('#spPriceValue')?.value)||0,p_sort_order:Number(q('#spPriceSort')?.value)||0});if(error)return notify(error.message);ok('Fiyatlandırma kaydedildi.');await window.loadView('pricing')})}return r};
  if(oldCustomers)window.customersView=async function(){const r=await oldCustomers.apply(this,arguments);await customerActions();await customerDelete();return r};
  if(oldEquipment)window.equipmentView=async function(){const r=await oldEquipment.apply(this,arguments);await equipmentActions();await equipmentDelete();return r};
  window.respondJob=async(id,response)=>{const permission=response==='accepted'?'jobs.accept':'jobs.reject';if(!can(permission)&&!can('jobs.manage'))return notify(response==='accepted'?'İş kabul yetkiniz yok.':'İş reddetme yetkiniz yok.');const {error}=await sb.rpc('staff_respond_job',{p_job_id:id,p_response:response,p_note:null});if(error)return notify(error.message);ok(response==='accepted'?'İş kabul edildi.':'İş reddedildi.');await window.loadView('jobs')};
  window.setJobStatus=async(id,status)=>{if(!can('jobs.status.update')&&!can('jobs.manage'))return notify('İş durumu değiştirme yetkiniz yok.');const {error}=await sb.rpc('staff_update_job_status',{p_job_id:id,p_status:status});if(error)return notify(error.message);ok('İş durumu güncellendi.');await window.loadView('jobs')};
  window.updateJobNotes=async id=>{if(!can('jobs.notes.update')&&!can('jobs.manage'))return notify('İş notu düzenleme yetkiniz yok.');const note=prompt('İş notu','');if(note===null)return;const {error}=await sb.rpc('staff_update_job_notes',{p_job_id:id,p_notes:note});if(error)return notify(error.message);ok('İş notu kaydedildi.');await window.loadView('jobs')};
})();
