import { cors,json,options,clients,requireUser,sha256,err } from "../_shared/core.ts";
const NEED=new Set(["github.file_write","github.push","github.merge","github.open_pr","db.delete","db.bulk_update","pricing.update","deploy","permission.change","agent.create","agent.delete","agent.grant_tool","quotes.send"]);
const ALIASES:Record<string,string[]>={list_leads:["teklifler","leads","contacts"],"leads.list":["teklifler","leads","contacts"],list_events:["event_projects","events","etkinlikler"],"events.list":["event_projects","events","etkinlikler"],equipment_status:["equipment","ekipman","technical_specs"],"equipment.list":["equipment","ekipman","technical_specs"],list_staff:["staff","personnel","personel"],"staff.list":["staff","personnel","personel"]};
async function readTable(admin:any,tool:string,limit:number){const errors:string[]=[];for(const table of ALIASES[tool]||[]){const {data,error}=await admin.from(table).select("*").limit(limit);if(!error)return{table,items:data||[],count:(data||[]).length};errors.push(`${table}: ${error.message}`)}return{table:null,items:[],count:0,note:errors.join(" | ")||"Tablo yok"}}
async function ghRead(tool:string,p:any){const token=Deno.env.get("GITHUB_TOKEN");if(!token)throw new Error("GITHUB_TOKEN secret eksik");const owner=Deno.env.get("GITHUB_OWNER")||"ibrahimFOH",repo=Deno.env.get("GITHUB_REPO")||"Stagepulse.hatay",branch=String(p.branch||"main"),h={Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(tool==="repo.tree"){const r=await fetch(`https://api.github.com/repos/${owner}/${repo}/git/trees/${encodeURIComponent(branch)}?recursive=1`,{headers:h});if(!r.ok)throw new Error("Repo ağacı alınamadı");const d=await r.json();return{owner,repo,branch,files:(d.tree||[]).filter((x:any)=>x.type==="blob").map((x:any)=>x.path).slice(0,1000)}}const path=String(p.path||"");if(!path||path.includes("..")||path.startsWith("/"))throw new Error("Geçersiz path");const r=await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(path).replace(/%2F/g,"/")}?ref=${encodeURIComponent(branch)}`,{headers:h});if(!r.ok)throw new Error("Dosya okunamadı");const d=await r.json();const content=new TextDecoder().decode(Uint8Array.from(atob(String(d.content).replace(/\n/g,"")),c=>c.charCodeAt(0)));return{owner,repo,branch,path:d.path,sha:d.sha,content}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return options();try{const user=await requireUser(req,true),{admin}=clients(req);if(req.method!=="POST")return json({error:"POST gerekli"},405);const b=await req.json(),tool=String(b.tool||""),p=(b.params||{}) as Record<string,unknown>;
if(["repo.tree","repo.read_file"].includes(tool))return json({status:"ok",result:await ghRead(tool,p)});
if(["github_status","github.status"].includes(tool)){const token=Deno.env.get("GITHUB_TOKEN");return json({status:"ok",result:{owner:Deno.env.get("GITHUB_OWNER")||"ibrahimFOH",repo:Deno.env.get("GITHUB_REPO")||"Stagepulse.hatay",branch:String(p.branch||"main"),configured:Boolean(token)}})}
if(ALIASES[tool]){const result=await readTable(admin,tool,Math.min(Number(p.limit)||50,100));await admin.from("jarvis_audit").insert({actor:user.id,mode:"patron",event_type:"tool.read",body:{tool,table:result.table,count:result.count}});return json({status:"ok",result})}
if(tool==="agents.list"){const {data,error}=await admin.from("jarvis_agents").select("id,name,mode,tools,status,created_at,updated_at").order("created_at",{ascending:false});if(error)throw error;return json({status:"ok",result:{items:data||[],count:(data||[]).length}})}
if(tool==="approvals.list"){const {data,error}=await admin.from("jarvis_approvals").select("id,type,status,preview,payload,created_at,requested_by").eq("status","pending").order("created_at",{ascending:false}).limit(50);if(error)throw error;return json({status:"ok",result:{items:data||[],count:(data||[]).length}})}
const type=tool==="repo.open_pr"?"github.open_pr":(tool==="repo.propose_change"||tool==="propose_code_change"?"github.file_write":(NEED.has(tool)?tool:""));
if(type){const approval={id:"ap_"+crypto.randomUUID(),type,status:"pending",requested_by:"patron",requested_by_user:user.id,preview:{title:p.title||`${tool} onayı`,risk:"high",diff_summary:p.diff_summary||p.instruction||"Patron onayı gerekli"},payload:p,payload_hash:await sha256(p)};const {error}=await admin.from("jarvis_approvals").insert(approval);if(error)throw error;await admin.from("jarvis_audit").insert({actor:user.id,mode:"patron",event_type:"approval.created",body:{approval_id:approval.id,type}});return json({status:"pending_approval",approval_id:approval.id,approval})}
throw new Error("Bilinmeyen araç: "+tool)}catch(e){return err(e)}});
