import { json, options, withPatron, sha256, err } from "../_shared/core.ts";
const NEED=new Set(["github.file_write","github.push","github.merge","github.open_pr","db.delete","db.bulk_update","pricing.update","deploy","permission.change","agent.create","agent.delete","agent.grant_tool","quotes.send"]);
const ALIASES:any={"list_leads":["teklifler","leads","contacts"],"leads.list":["teklifler","leads","contacts"],"list_events":["event_projects","events","etkinlikler"],"events.list":["event_projects","events","etkinlikler"],equipment_status:["equipment","ekipman","technical_specs"],"equipment.list":["equipment","ekipman","technical_specs"],list_staff:["staff","personnel","personel"],"staff.list":["staff","personnel","personel"]};
async function table(admin:any,tool:string,limit:number){for(const t of ALIASES[tool]||[]){const r=await admin.from(t).select("*").limit(limit);if(!r.error)return{table:t,items:r.data||[],count:(r.data||[]).length};}return{table:null,items:[],count:0};}
async function ghRead(tool:string,p:any){const token=Deno.env.get("GITHUB_TOKEN");if(!token)throw Error("GITHUB_TOKEN secret eksik");const o=Deno.env.get("GITHUB_OWNER")||"ibrahimFOH",r=Deno.env.get("GITHUB_REPO")||"Stagepulse.hatay",b=String(p.branch||"main"),h={Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(tool==="repo.tree"){const x=await fetch(`https://api.github.com/repos/${o}/${r}/git/trees/${encodeURIComponent(b)}?recursive=1`,{headers:h});if(!x.ok)throw Error("Repo ağacı alınamadı");const d=await x.json();return{owner:o,repo:r,branch:b,files:(d.tree||[]).filter((z:any)=>z.type==="blob").map((z:any)=>z.path)}}const path=String(p.path||"");if(!path||path.includes("..")||path.startsWith("/"))throw Error("Geçersiz path");const x=await fetch(`https://api.github.com/repos/${o}/${r}/contents/${encodeURIComponent(path).replace(/%2F/g,"/")}?ref=${encodeURIComponent(b)}`,{headers:h});if(!x.ok)throw Error("Dosya okunamadı");const d=await x.json();return{owner:o,repo:r,branch:b,path:d.path,sha:d.sha,content:new TextDecoder().decode(Uint8Array.from(atob(String(d.content).replace(/\n/g,"")),c=>c.charCodeAt(0)))}}
async function makeApproval(admin:any,userId:string,type:string,p:any){const payload=JSON.parse(JSON.stringify(p||{})),id="ap_"+crypto.randomUUID(),a={id,type,status:"pending",requested_by:"patron",requested_by_user:userId,preview:{title:p.title||`${type} onayı`,risk:"high",diff_summary:p.diff_summary||p.instruction||type},payload,payload_hash:await sha256(payload),idempotency_key:crypto.randomUUID()};const r=await admin.from("jarvis_approvals").insert(a).select().single();if(r.error)throw r.error;await admin.from("jarvis_audit").insert({actor:userId,mode:"patron",event_type:"approval.created",body:{approval_id:id,type}});return{status:"pending_approval",approval_id:id,approval:a};}
Deno.serve(withPatron(async(req:any,ctx:any,user:any)=>{if(req.method==="OPTIONS")return options();try{if(req.method!=="POST")return json({error:"POST gerekli"},405);const admin=ctx.supabaseAdmin,b=await req.json(),tool=String(b.tool||""),p=(b.params||{}) as Record<string,unknown>;
if(tool==="repo.tree"||tool==="repo.read_file")return json({status:"ok",result:await ghRead(tool,p)});
if(tool==="github_status"||tool==="github.status")return json({status:"ok",result:{owner:Deno.env.get("GITHUB_OWNER")||"ibrahimFOH",repo:Deno.env.get("GITHUB_REPO")||"Stagepulse.hatay",branch:String(p.branch||"main"),configured:Boolean(Deno.env.get("GITHUB_TOKEN"))}});
if(ALIASES[tool]){const result=await table(admin,tool,Math.min(Number(p.limit)||50,100));await admin.from("jarvis_audit").insert({actor:user.id,mode:"patron",event_type:"tool.read",body:{tool,table:result.table,count:result.count}});return json({status:"ok",result});}
if(tool==="agents.list"){const r=await admin.from("jarvis_agents").select("id,name,mode,tools,status,created_at,updated_at").order("created_at",{ascending:false});if(r.error)throw r.error;return json({status:"ok",result:{items:r.data||[],count:(r.data||[]).length}})}
if(tool==="approvals.list"){const r=await admin.from("jarvis_approvals").select("id,type,status,preview,payload,created_at,requested_by").eq("status","pending").order("created_at",{ascending:false}).limit(50);if(r.error)throw r.error;return json({status:"ok",result:{items:r.data||[],count:(r.data||[]).length}})}
if(NEED.has(tool)||tool==="repo.propose_change"||tool==="propose_code_change"){const type=tool==="repo.propose_change"||tool==="propose_code_change"?"github.file_write":tool;return json(await makeApproval(admin,user.id,type,p));}
throw Error("Bilinmeyen araç: "+tool);}catch(e){return err(e)}}));
