begin;
revoke execute on function public.is_org_owner() from anon;
revoke execute on function public.is_org_owner() from authenticated;
grant execute on function public.is_org_owner() to authenticated;
revoke execute on function public.org_role_tier_for(uuid) from anon;
revoke execute on function public.org_role_tier_for(uuid) from authenticated;
grant execute on function public.org_role_tier_for(uuid) to authenticated;
revoke execute on function public.org_scope(uuid) from anon;
revoke execute on function public.org_scope(uuid) from authenticated;
grant execute on function public.org_scope(uuid) to authenticated;
revoke execute on function public.can_view_org_member(uuid) from anon;
revoke execute on function public.can_view_org_member(uuid) from authenticated;
grant execute on function public.can_view_org_member(uuid) to authenticated;
revoke execute on function public.owner_set_org_membership(uuid,text,text,uuid,uuid,uuid,boolean) from anon;
revoke execute on function public.owner_set_org_membership(uuid,text,text,uuid,uuid,uuid,boolean) from authenticated;
grant execute on function public.owner_set_org_membership(uuid,text,text,uuid,uuid,uuid,boolean) to authenticated;
revoke execute on function public.owner_set_admin_capability(uuid,text,boolean) from anon;
revoke execute on function public.owner_set_admin_capability(uuid,text,boolean) from authenticated;
grant execute on function public.owner_set_admin_capability(uuid,text,boolean) to authenticated;
commit;
