create table if not exists public.app_versions (
  id bigint generated by default as identity primary key,
  platform text not null check (platform in ('admin','staff')),
  web_version text,
  apk_version integer,
  minimum_version integer,
  apk_url text,
  apk_sha256 text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_versions_platform_key unique (platform),
  constraint app_versions_version_check check (
    (apk_version is null or apk_version >= 0)
    and (minimum_version is null or minimum_version >= 0)
  )
);

alter table public.app_versions enable row level security;

revoke all on public.app_versions from anon, authenticated;
grant select on public.app_versions to anon, authenticated;

create policy app_versions_public_select
on public.app_versions
for select
to anon, authenticated
using (true);

create policy app_versions_admin_insert
on public.app_versions
for insert
to authenticated
with check (private.is_admin());

create policy app_versions_admin_update
on public.app_versions
for update
to authenticated
using (private.is_admin())
with check (private.is_admin());

create or replace function public.app_versions_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_versions_set_updated_at on public.app_versions;
create trigger app_versions_set_updated_at
before update on public.app_versions
for each row execute function public.app_versions_set_updated_at();

insert into public.app_versions (platform, web_version, apk_version, minimum_version, apk_url, apk_sha256, notes)
values
  ('staff', '2026.08.23.03', 3, 3, null, null, 'Initial release-control record'),
  ('admin', '2026.08.23.03', 3, 3, null, null, 'Initial release-control record')
on conflict (platform) do nothing;
