-- Stagepulse canonical RBAC CRUD matrix: every management area gets granular actions.
begin;
insert into public.admin_capabilities(key,category,name,description,active)
select v.key,v.category,v.name,v.description,true from (values
('dashboard.manage','Genel Bakış','Genel bakışı yönetme','KPI ve özet ekranı yönetimi'),('dashboard.delete','Genel Bakış','Genel bakış kayıtlarını silme','Yönetim özet kayıtlarını silme'),('dashboard.export','Genel Bakış','Genel bakışı dışa aktarma','Genel bakış verilerini dışa aktarma'),
('offers.create','Teklifler','Teklif oluşturma','Yeni teklif oluşturma'),('offers.update','Teklifler','Teklif düzenleme','Teklif düzenleme'),('offers.delete','Teklifler','Teklif silme','Teklif silme'),('offers.export','Teklifler','Teklif dışa aktarma','Teklif dışa aktarma'),
('customers.create','Müşteriler','Müşteri oluşturma','Müşteri oluşturma'),('customers.update','Müşteriler','Müşteri düzenleme','Müşteri düzenleme'),('customers.delete','Müşteriler','Müşteri silme','Müşteri silme'),('customers.export','Müşteriler','Müşteri dışa aktarma','Müşteri dışa aktarma'),
('jobs.create','İşler','İş oluşturma','İş oluşturma'),('jobs.update','İşler','İş düzenleme','İş düzenleme'),('jobs.delete','İşler','İş silme','İş silme'),('jobs.assign','İşler','İş görevlendirme','Personel ve kaynak atama'),('jobs.export','İşler','İş dışa aktarma','İş dışa aktarma'),
('equipment.create','Ekipman','Ekipman oluşturma','Ekipman oluşturma'),('equipment.update','Ekipman','Ekipman düzenleme','Ekipman düzenleme'),('equipment.delete','Ekipman','Ekipman silme','Ekipman silme'),('equipment.assign','Ekipman','Ekipman görevlendirme','Ekipman atama'),('equipment.export','Ekipman','Ekipman dışa aktarma','Ekipman dışa aktarma'),
('staff.create','Personel','Personel oluşturma','Personel oluşturma'),('staff.update','Personel','Personel düzenleme','Personel düzenleme'),('staff.delete','Personel','Personel silme','Personel pasifleştirme veya silme'),('staff.assign','Personel','Personel görevlendirme','Personel atama'),('staff.permissions.manage','Personel','Personel yetkilerini yönetme','Personel yetkilerini yönetme'),('staff.export','Personel','Personel dışa aktarma','Personel dışa aktarma'),
('finance.create','Finans','Finans kaydı oluşturma','Finans kaydı oluşturma'),('finance.update','Finans','Finans kaydı düzenleme','Finans kaydı düzenleme'),('finance.delete','Finans','Finans kaydı silme','Finans kaydı silme'),('finance.export','Finans','Finans dışa aktarma','Finans dışa aktarma'),
('vehicles.create','Araçlar','Araç oluşturma','Araç oluşturma'),('vehicles.update','Araçlar','Araç düzenleme','Araç düzenleme'),('vehicles.delete','Araçlar','Araç silme','Araç silme'),('vehicles.export','Araçlar','Araç dışa aktarma','Araç dışa aktarma'),
('documents.create','Dosyalar','Doküman oluşturma','Doküman oluşturma'),('documents.update','Dosyalar','Doküman düzenleme','Doküman düzenleme'),('documents.delete','Dosyalar','Doküman silme','Doküman silme'),('documents.export','Dosyalar','Doküman dışa aktarma','Doküman dışa aktarma'),
('suppliers.create','Tedarikçiler','Tedarikçi oluşturma','Tedarikçi oluşturma'),('suppliers.update','Tedarikçiler','Tedarikçi düzenleme','Tedarikçi düzenleme'),('suppliers.delete','Tedarikçiler','Tedarikçi silme','Tedarikçi silme'),('suppliers.export','Tedarikçiler','Tedarikçi dışa aktarma','Tedarikçi dışa aktarma'),
('contracts.create','Sözleşmeler','Sözleşme oluşturma','Sözleşme oluşturma'),('contracts.update','Sözleşmeler','Sözleşme düzenleme','Sözleşme düzenleme'),('contracts.delete','Sözleşmeler','Sözleşme silme','Sözleşme silme'),('contracts.export','Sözleşmeler','Sözleşme dışa aktarma','Sözleşme dışa aktarma'),
('risks.create','Risk Yönetimi','Risk oluşturma','Risk oluşturma'),('risks.update','Risk Yönetimi','Risk düzenleme','Risk düzenleme'),('risks.delete','Risk Yönetimi','Risk silme','Risk silme'),('risks.export','Risk Yönetimi','Risk dışa aktarma','Risk dışa aktarma'),
('decisions.create','Yönetim','Karar oluşturma','Karar oluşturma'),('decisions.update','Yönetim','Karar düzenleme','Karar düzenleme'),('decisions.delete','Yönetim','Karar silme','Karar silme'),('decisions.export','Yönetim','Karar dışa aktarma','Karar dışa aktarma'),
('reports.manage','Raporlar','Raporları yönetme','Rapor tanımlarını yönetme'),('reports.delete','Raporlar','Rapor silme','Rapor silme'),
('maintenance.create','Envanter','Bakım kaydı oluşturma','Bakım kaydı oluşturma'),('maintenance.update','Envanter','Bakım kaydı düzenleme','Bakım kaydı düzenleme'),('maintenance.delete','Envanter','Bakım kaydı silme','Bakım kaydı silme'),
('notifications.delete','Bildirimler','Bildirim silme','Bildirim silme'),('automation.create','Otomasyon','Otomasyon oluşturma','Otomasyon oluşturma'),('automation.update','Otomasyon','Otomasyon düzenleme','Otomasyon düzenleme'),('automation.delete','Otomasyon','Otomasyon silme','Otomasyon silme'),
('ai.create','Yapay Zeka','AI işlemi oluşturma','AI görevi oluşturma'),('ai.update','Yapay Zeka','AI işlemi düzenleme','AI kaydı düzenleme'),('ai.delete','Yapay Zeka','AI işlemi silme','AI kaydı silme'),
('marketing.create','Pazarlama','Pazarlama oluşturma','Kampanya oluşturma'),('marketing.update','Pazarlama','Pazarlama düzenleme','Kampanya düzenleme'),('marketing.delete','Pazarlama','Pazarlama silme','Kampanya silme'),('marketing.export','Pazarlama','Pazarlama dışa aktarma','Kampanya dışa aktarma'),
('site.media.view','Site','Site medyasını görüntüleme','Site medyasını görüntüleme'),('site.media.create','Site','Site medyası ekleme','Siteye medya ekleme'),('site.media.update','Site','Site medyasını düzenleme','Site medyasını düzenleme'),('site.media.delete','Site','Site medyasını silme','Site medyasını silme'),
('system.audit.view','Sistem','Denetim kayıtlarını görüntüleme','Audit kayıtlarını görüntüleme'),('system.audit.export','Sistem','Denetim kayıtlarını dışa aktarma','Audit kayıtlarını dışa aktarma'),('system.users.manage','Kullanıcı ve Güvenlik','Kullanıcıları yönetme','Kullanıcı erişimlerini yönetme'),('system.roles.manage','Kullanıcı ve Güvenlik','Rolleri yönetme','Rol ve yetkileri yönetme')
) v(key,category,name,description) on conflict(key) do update set category=excluded.category,name=excluded.name,description=excluded.description,active=true;
commit;
