begin;
revoke all on function public.notify_new_quote() from public, anon, authenticated;
revoke all on function public.next_quote_number() from public, anon, authenticated;
revoke all on function public.ensure_job_for_offer(uuid) from public, anon, authenticated;
revoke all on function public.ensure_quote_public_code(uuid) from public, anon, authenticated;
revoke all on function public.org_panel_context(uuid) from public, anon, authenticated;
revoke all on function public.org_visible_member_ids(uuid) from public, anon, authenticated;
revoke all on function public.org_role_tier_for(uuid) from public, anon, authenticated;
revoke all on function public.org_scope(uuid) from public, anon, authenticated;
grant execute on function public.ensure_quote_public_code(uuid) to authenticated;
grant execute on function public.org_panel_context(uuid) to authenticated;
grant execute on function public.org_visible_member_ids(uuid) to authenticated;
grant execute on function public.org_role_tier_for(uuid) to authenticated;
grant execute on function public.org_scope(uuid) to authenticated;
revoke all on function public.admin_create_price_rule(text,text,numeric,text) from public, anon; grant execute on function public.admin_create_price_rule(text,text,numeric,text) to authenticated;
revoke all on function public.admin_create_service(text,text,numeric,numeric,integer,integer,integer,numeric,numeric,numeric,numeric) from public, anon; grant execute on function public.admin_create_service(text,text,numeric,numeric,integer,integer,integer,numeric,numeric,numeric,numeric) to authenticated;
revoke all on function public.admin_set_price_rule_active(uuid,boolean) from public, anon; grant execute on function public.admin_set_price_rule_active(uuid,boolean) to authenticated;
revoke all on function public.admin_set_service_active(uuid,boolean) from public, anon; grant execute on function public.admin_set_service_active(uuid,boolean) to authenticated;
revoke all on function public.admin_update_ai_agent(text,boolean,boolean,boolean,boolean) from public, anon; grant execute on function public.admin_update_ai_agent(text,boolean,boolean,boolean,boolean) to authenticated;
revoke all on function public.admin_update_price_rule(uuid,numeric,boolean,text) from public, anon; grant execute on function public.admin_update_price_rule(uuid,numeric,boolean,text) to authenticated;
revoke all on function public.admin_update_service_pricing(uuid,numeric,numeric,integer,integer,integer,numeric,numeric,numeric,numeric,boolean) from public, anon; grant execute on function public.admin_update_service_pricing(uuid,numeric,numeric,integer,integer,integer,numeric,numeric,numeric,numeric,boolean) to authenticated;
revoke all on function public.is_org_owner() from public, anon; grant execute on function public.is_org_owner() to authenticated;
revoke all on function public.org_owner_catalog() from public, anon; grant execute on function public.org_owner_catalog() to authenticated;
revoke all on function public.owner_set_admin_capability(uuid,text,boolean) from public, anon; grant execute on function public.owner_set_admin_capability(uuid,text,boolean) to authenticated;
revoke all on function public.owner_set_org_membership(uuid,text,text,uuid,uuid,uuid,boolean) from public, anon; grant execute on function public.owner_set_org_membership(uuid,text,text,uuid,uuid,uuid,boolean) to authenticated;
revoke execute on function public.get_public_quote_by_code(text) from public; grant execute on function public.get_public_quote_by_code(text) to anon, authenticated;
revoke execute on function public.respond_to_quote_code(text,text) from public; grant execute on function public.respond_to_quote_code(text,text) to anon, authenticated;
commit;
