REVOKE ALL ON public.customers_staff FROM anon;
REVOKE ALL ON public.equipment_financial_staff FROM anon;
REVOKE ALL ON public.equipment_staff FROM anon;
REVOKE ALL ON public.my_jobs_staff FROM anon;
REVOKE ALL ON public.offers_financial_staff FROM anon;
REVOKE ALL ON public.offers_staff FROM anon;
REVOKE ALL ON public.payments_staff FROM anon;
REVOKE ALL ON public.pricing FROM anon;
REVOKE ALL ON public.pricing_staff FROM anon;
REVOKE ALL ON public.event_types FROM anon;
REVOKE ALL ON public.services FROM anon;
GRANT SELECT ON public.event_types TO anon;
GRANT SELECT ON public.services TO anon;
NOTIFY pgrst,'reload schema';
