DROP POLICY IF EXISTS notification_devices_self_select ON public.notification_devices;
CREATE POLICY notification_devices_self_select ON public.notification_devices FOR SELECT TO authenticated USING (user_id = (select auth.uid()));
DROP POLICY IF EXISTS notification_devices_self_insert ON public.notification_devices;
CREATE POLICY notification_devices_self_insert ON public.notification_devices FOR INSERT TO authenticated WITH CHECK (user_id = (select auth.uid()));
DROP POLICY IF EXISTS notification_devices_self_update ON public.notification_devices;
CREATE POLICY notification_devices_self_update ON public.notification_devices FOR UPDATE TO authenticated USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
DROP POLICY IF EXISTS notification_devices_self_delete ON public.notification_devices;
CREATE POLICY notification_devices_self_delete ON public.notification_devices FOR DELETE TO authenticated USING (user_id = (select auth.uid()));
DROP POLICY IF EXISTS staff_profiles_self_update ON public.staff_profiles;
CREATE POLICY staff_profiles_self_update ON public.staff_profiles FOR UPDATE TO authenticated USING (user_id = (select auth.uid()) AND active = true) WITH CHECK (user_id = (select auth.uid()) AND active = true);
