begin;
alter function public.coalesce_quote_numeric_fields() set search_path = public, pg_temp;
alter function public.normalize_offer_numeric_fields() set search_path = public, pg_temp;
revoke all on function public.notify_new_quote() from anon, authenticated;
revoke all on function public.next_quote_number() from anon, authenticated;
revoke all on function public.ensure_job_for_offer(uuid) from anon, authenticated;
revoke execute on function public.admin_create_price_rule(text,text,numeric,text) from anon;
revoke execute on function public.admin_create_service(text,text,numeric,numeric,integer,integer,integer,numeric,numeric,numeric,numeric) from anon;
revoke execute on function public.admin_set_price_rule_active(uuid,boolean) from anon;
revoke execute on function public.admin_set_service_active(uuid,boolean) from anon;
revoke execute on function public.admin_update_ai_agent(text,boolean,boolean,boolean,boolean) from anon;
revoke execute on function public.admin_update_price_rule(uuid,numeric,boolean,text) from anon;
revoke execute on function public.admin_update_service_pricing(uuid,numeric,numeric,integer,integer,integer,numeric,numeric,numeric,numeric,boolean) from anon;
create or replace function public.ensure_quote_public_code(p_offer_id uuid) returns text language plpgsql security definer set search_path=public,pg_temp as $$ declare v_code text; begin if auth.uid() is null then raise exception 'Oturum gerekli.' using errcode='42501'; end if; if not public.staff_can_any(array['offers.view','offers.manage']) then raise exception 'Teklif görüntüleme yetkisi gerekli.' using errcode='42501'; end if; select public_code into v_code from public.teklifler where id=p_offer_id; if not found then raise exception 'Teklif bulunamadı.'; end if; if v_code is not null and v_code<>'' then return v_code; end if; loop v_code:=upper(substr(encode(gen_random_bytes(6),'hex'),1,10)); exit when not exists(select 1 from public.teklifler where public_code=v_code); end loop; update public.teklifler set public_code=v_code,updated_at=now() where id=p_offer_id; return v_code; end; $$;
revoke execute on function public.ensure_quote_public_code(uuid) from anon;
grant execute on function public.ensure_quote_public_code(uuid) to authenticated;
create or replace function public.org_panel_context(p_user_id uuid default auth.uid()) returns table(role_code text,position_name text,department_id uuid,region_id uuid,manager_user_id uuid,panel_code text,scope_mode text,is_owner boolean) language sql stable security definer set search_path=public,pg_temp as $$ select r.code,p.name,m.department_id,m.region_id,m.manager_user_id,pr.panel_code,pr.scope_mode,(r.code='owner') from public.org_memberships m join public.org_roles r on r.id=m.role_id left join public.org_positions p on p.id=m.position_id left join public.org_panel_rules pr on pr.role_code=r.code where m.user_id=case when p_user_id is null then auth.uid() when p_user_id=auth.uid() then auth.uid() when public.is_org_owner() then p_user_id else auth.uid() end and m.active=true limit 1; $$;
create or replace function public.org_visible_member_ids(p_user_id uuid default auth.uid()) returns table(user_id uuid) language sql stable security definer set search_path=public,pg_temp as $$ with me as (select m.user_id,m.department_id,m.region_id,r.code role_code from public.org_memberships m join public.org_roles r on r.id=m.role_id where m.user_id=case when p_user_id is null then auth.uid() when p_user_id=auth.uid() then auth.uid() when public.is_org_owner() then p_user_id else auth.uid() end and m.active=true limit 1) select m.user_id from public.org_memberships m,me where m.active=true and (me.role_code='owner' or me.role_code in ('super_admin','upper_admin','ceo') or (me.role_code='department_manager' and m.department_id=me.department_id) or (me.role_code='regional_manager' and m.region_id=me.region_id) or (me.role_code='employee' and m.user_id=me.user_id)); $$;
create or replace function public.org_role_tier_for(p_user_id uuid default auth.uid()) returns integer language sql stable security definer set search_path=public,pg_temp as $$ select coalesce((select r.tier from public.org_memberships om join public.org_roles r on r.id=om.role_id where om.user_id=case when p_user_id is null or p_user_id=auth.uid() or public.is_org_owner() then coalesce(p_user_id,auth.uid()) else auth.uid() end and om.active limit 1),99); $$;
create or replace function public.org_scope(p_user_id uuid default auth.uid()) returns jsonb language sql stable security definer set search_path=public,pg_temp as $$ select coalesce((select jsonb_build_object('user_id',om.user_id,'role',r.code,'tier',r.tier,'department_id',om.department_id,'region_id',om.region_id,'manager_user_id',om.manager_user_id,'is_owner',(r.code='owner'),'is_admin',r.is_admin_role,'active',om.active) from public.org_memberships om join public.org_roles r on r.id=om.role_id where om.user_id=case when p_user_id is null or p_user_id=auth.uid() or public.is_org_owner() then coalesce(p_user_id,auth.uid()) else auth.uid() end and om.active limit 1),'{}'::jsonb); $$;
drop policy if exists org_roles_authenticated_read on public.org_roles; create policy org_roles_authenticated_read on public.org_roles for select to authenticated using (active=true);
drop policy if exists org_positions_authenticated_read on public.org_positions; create policy org_positions_authenticated_read on public.org_positions for select to authenticated using (active=true);
drop policy if exists org_departments_authenticated_read on public.org_departments; create policy org_departments_authenticated_read on public.org_departments for select to authenticated using (active=true);
drop policy if exists org_regions_authenticated_read on public.org_regions; create policy org_regions_authenticated_read on public.org_regions for select to authenticated using (active=true);
drop policy if exists org_panel_rules_authenticated_read on public.org_panel_rules; create policy org_panel_rules_authenticated_read on public.org_panel_rules for select to authenticated using (active=true);
drop policy if exists admin_capabilities_authenticated_read on public.admin_capabilities; create policy admin_capabilities_authenticated_read on public.admin_capabilities for select to authenticated using (active=true);
drop policy if exists org_memberships_self_or_owner_read on public.org_memberships; create policy org_memberships_self_or_owner_read on public.org_memberships for select to authenticated using (user_id=auth.uid() or public.is_org_owner());
drop policy if exists admin_capability_grants_owner_read on public.admin_capability_grants; create policy admin_capability_grants_owner_read on public.admin_capability_grants for select to authenticated using (public.is_org_owner());
create index if not exists admin_capability_grants_capability_key_idx on public.admin_capability_grants(capability_key);
create index if not exists admin_capability_grants_granted_by_idx on public.admin_capability_grants(granted_by);
create index if not exists equipment_movements_from_location_idx on public.equipment_movements(from_location_id);
create index if not exists equipment_movements_from_user_idx on public.equipment_movements(from_user_id);
create index if not exists equipment_movements_to_location_idx on public.equipment_movements(to_location_id);
create index if not exists equipment_movements_to_user_idx on public.equipment_movements(to_user_id);
create index if not exists offer_items_equipment_id_idx on public.offer_items(equipment_id);
create index if not exists org_departments_manager_user_idx on public.org_departments(manager_user_id);
create index if not exists org_memberships_department_idx on public.org_memberships(department_id);
create index if not exists org_memberships_manager_user_idx on public.org_memberships(manager_user_id);
create index if not exists org_memberships_position_idx on public.org_memberships(position_id);
create index if not exists org_memberships_region_idx on public.org_memberships(region_id);
create index if not exists org_memberships_role_idx on public.org_memberships(role_id);
create index if not exists org_regions_manager_user_idx on public.org_regions(manager_user_id);
drop policy if exists approval_request_self_insert on public.approval_requests; create policy approval_request_self_insert on public.approval_requests for insert to authenticated with check (requested_by=(select auth.uid()) and status='pending');
drop policy if exists event_resources_assigned_read on public.event_resources; create policy event_resources_assigned_read on public.event_resources for select to authenticated using (private.is_admin() or private.is_user_assigned_to_event(event_id) or staff_user_id=(select auth.uid()));
commit;
