begin;
revoke execute on function public.admin_update_business_settings(jsonb) from public;
grant execute on function public.admin_update_business_settings(jsonb) to authenticated;
revoke execute on function public.evaluate_offer(uuid) from public;
grant execute on function public.evaluate_offer(uuid) to authenticated;
revoke execute on function public.get_my_staff_settings() from public;
grant execute on function public.get_my_staff_settings() to authenticated;
revoke execute on function public.staff_assigned_offers() from public;
grant execute on function public.staff_assigned_offers() to authenticated;
revoke execute on function public.staff_claim_offer(uuid) from public;
grant execute on function public.staff_claim_offer(uuid) to authenticated;
revoke execute on function public.staff_incoming_offers() from public;
grant execute on function public.staff_incoming_offers() to authenticated;
revoke execute on function public.staff_evaluate_offer(uuid) from public;
grant execute on function public.staff_evaluate_offer(uuid) to authenticated;
revoke execute on function public.get_my_staff_permissions() from public;
grant execute on function public.get_my_staff_permissions() to authenticated;
revoke execute on function public.get_my_staff_profile() from public;
grant execute on function public.get_my_staff_profile() to authenticated;
revoke execute on function public.staff_capabilities(uuid) from public;
grant execute on function public.staff_capabilities(uuid) to authenticated;
revoke execute on function public.staff_capability(text) from public;
grant execute on function public.staff_capability(text) to authenticated;
revoke execute on function public.staff_has_perm(text) from public;
grant execute on function public.staff_has_perm(text) to authenticated;
revoke execute on function public.staff_offer_response_safe(uuid,text,text) from public;
grant execute on function public.staff_offer_response_safe(uuid,text,text) to authenticated;
revoke execute on function public.staff_respond_job(uuid,text,text) from public;
grant execute on function public.staff_respond_job(uuid,text,text) to authenticated;
revoke execute on function public.staff_update_job_notes(uuid,text) from public;
grant execute on function public.staff_update_job_notes(uuid,text) to authenticated;
revoke execute on function public.staff_update_job_status(uuid,text) from public;
grant execute on function public.staff_update_job_status(uuid,text) to authenticated;
revoke execute on function public.staff_update_offer_event_date(uuid,date) from public;
grant execute on function public.staff_update_offer_event_date(uuid,date) to authenticated;
notify pgrst,'reload schema';
commit;
