-- Staff CRUD operations: all writes use SECURITY DEFINER RPCs with canonical staff permissions.
-- Production was applied as staffcrudoperationxy.

create or replace function public.staff_can_any(p_keys text[]) returns boolean language sql stable security definer set search_path='' as $$
select private.is_admin() or exists(select 1 from public.staff_permissions sp where sp.user_id=(select auth.uid()) and sp.enabled=true and sp.permission_key=any(p_keys));
$$;
revoke all on function public.staff_can_any(text[]) from public;
grant execute on function public.staff_can_any(text[]) to authenticated;

create or replace function public.staff_create_customer(p_name text,p_company text default null,p_phone text default null,p_email text default null,p_notes text default null) returns public.customers language plpgsql security definer set search_path='' as $$ declare r public.customers; begin if not public.staff_can_any(array['customers.create','customers.manage']) then raise exception 'Müşteri ekleme yetkiniz yok'; end if; insert into public.customers(name,company,phone,email,notes,last_contact_at) values(nullif(trim(p_name),''),nullif(trim(p_company),''),nullif(trim(p_phone),''),nullif(trim(p_email),''),nullif(trim(p_notes),''),now()) returning * into r; return r; end; $$;
revoke all on function public.staff_create_customer(text,text,text,text,text) from public;
grant execute on function public.staff_create_customer(text,text,text,text,text) to authenticated;

create or replace function public.staff_update_customer(p_id uuid,p_name text,p_company text default null,p_phone text default null,p_email text default null,p_notes text default null) returns public.customers language plpgsql security definer set search_path='' as $$ declare r public.customers; begin if not public.staff_can_any(array['customers.update','customers.manage']) then raise exception 'Müşteri düzenleme yetkiniz yok'; end if; update public.customers set name=nullif(trim(p_name),''),company=nullif(trim(p_company),''),phone=nullif(trim(p_phone),''),email=nullif(trim(p_email),''),notes=nullif(trim(p_notes),''),updated_at=now() where id=p_id returning * into r; if not found then raise exception 'Müşteri bulunamadı'; end if; return r; end; $$;
revoke all on function public.staff_update_customer(uuid,text,text,text,text,text) from public;
grant execute on function public.staff_update_customer(uuid,text,text,text,text,text) to authenticated;

create or replace function public.staff_upsert_service(p_id uuid,p_name text,p_description text default null,p_base_price numeric default 0,p_sort_order integer default 0) returns public.services language plpgsql security definer set search_path='' as $$ declare r public.services; begin if not public.staff_can_any(array['pricing.manage','pricing.update']) then raise exception 'Fiyatlandırma düzenleme yetkiniz yok'; end if; if p_id is null then insert into public.services(name,description,base_price,sort_order) values(nullif(trim(p_name),''),nullif(trim(p_description),''),coalesce(p_base_price,0),coalesce(p_sort_order,0)) returning * into r; else update public.services set name=nullif(trim(p_name),''),description=nullif(trim(p_description),''),base_price=coalesce(p_base_price,0),sort_order=coalesce(p_sort_order,0) where id=p_id returning * into r; end if; if r.id is null then raise exception 'Hizmet bulunamadı'; end if; return r; end; $$;
revoke all on function public.staff_upsert_service(uuid,text,text,numeric,integer) from public;
grant execute on function public.staff_upsert_service(uuid,text,text,numeric,integer) to authenticated;

create or replace function public.staff_update_price_rule(p_id uuid,p_value numeric,p_notes text default null) returns public.price_rules language plpgsql security definer set search_path='' as $$ declare r public.price_rules; begin if not public.staff_can_any(array['pricing.manage','pricing.update']) then raise exception 'Fiyat kuralı düzenleme yetkiniz yok'; end if; update public.price_rules set value=coalesce(p_value,0),notes=nullif(trim(p_notes),''),updated_at=now() where id=p_id returning * into r; if not found then raise exception 'Fiyat kuralı bulunamadı'; end if; return r; end; $$;
revoke all on function public.staff_update_price_rule(uuid,numeric,text) from public;
grant execute on function public.staff_update_price_rule(uuid,numeric,text) to authenticated;

create or replace function public.staff_upsert_equipment(p_id uuid,p_category text,p_brand text default null,p_model text default null,p_quantity integer default 0,p_notes text default null) returns public.equipment language plpgsql security definer set search_path='' as $$ declare r public.equipment; begin if not public.staff_can_any(array['equipment.manage','equipment.update']) then raise exception 'Ekipman düzenleme yetkiniz yok'; end if; if p_id is null then insert into public.equipment(category,brand,model,quantity,notes) values(nullif(trim(p_category),''),nullif(trim(p_brand),''),nullif(trim(p_model),''),greatest(coalesce(p_quantity,0),0),nullif(trim(p_notes),'')) returning * into r; else update public.equipment set category=nullif(trim(p_category),''),brand=nullif(trim(p_brand),''),model=nullif(trim(p_model),''),quantity=greatest(coalesce(p_quantity,0),0),notes=nullif(trim(p_notes),''),updated_at=now() where id=p_id returning * into r; end if; if r.id is null then raise exception 'Ekipman bulunamadı'; end if; return r; end; $$;
revoke all on function public.staff_upsert_equipment(uuid,text,text,text,integer,text) from public;
grant execute on function public.staff_upsert_equipment(uuid,text,text,text,integer,text) to authenticated;

create or replace function public.staff_create_offer(p_name text,p_company text default null,p_phone text default null,p_email text default null,p_type text default null,p_event_type text default null,p_location text default null,p_people integer default null,p_event_date date default null,p_message text default null,p_total numeric default 0,p_services jsonb default '[]'::jsonb) returns public.teklifler language plpgsql security definer set search_path='' as $$ declare r public.teklifler; begin if not public.staff_can_any(array['offers.create','offers.manage']) then raise exception 'Teklif oluşturma yetkiniz yok'; end if; insert into public.teklifler(name,company,phone,email,type,event_type,location,people,event_date,message,total,estimated_price,services,status) values(nullif(trim(p_name),''),nullif(trim(p_company),''),nullif(trim(p_phone),''),nullif(trim(p_email),''),nullif(trim(p_type),''),nullif(trim(p_event_type),''),nullif(trim(p_location),''),p_people,p_event_date,nullif(trim(p_message),''),greatest(coalesce(p_total,0),0),greatest(coalesce(p_total,0),0),coalesce(p_services,'[]'::jsonb),'new') returning * into r; return r; end; $$;
revoke all on function public.staff_create_offer(text,text,text,text,text,text,text,integer,date,text,numeric,jsonb) from public;
grant execute on function public.staff_create_offer(text,text,text,text,text,text,text,integer,date,text,numeric,jsonb) to authenticated;

create or replace function public.staff_update_offer(p_id uuid,p_name text,p_company text default null,p_phone text default null,p_email text default null,p_location text default null,p_people integer default null,p_event_date date default null,p_message text default null,p_total numeric default 0,p_services jsonb default '[]'::jsonb) returns public.teklifler language plpgsql security definer set search_path='' as $$ declare r public.teklifler; begin if not public.staff_can_any(array['offers.update','offers.manage']) then raise exception 'Teklif düzenleme yetkiniz yok'; end if; update public.teklifler set name=nullif(trim(p_name),''),company=nullif(trim(p_company),''),phone=nullif(trim(p_phone),''),email=nullif(trim(p_email),''),location=nullif(trim(p_location),''),people=p_people,event_date=p_event_date,message=nullif(trim(p_message),''),total=greatest(coalesce(p_total,0),0),estimated_price=greatest(coalesce(p_total,0),0),services=coalesce(p_services,'[]'::jsonb),updated_at=now() where id=p_id returning * into r; if not found then raise exception 'Teklif bulunamadı'; end if; return r; end; $$;
revoke all on function public.staff_update_offer(uuid,text,text,text,text,text,integer,date,text,numeric,jsonb) from public;
grant execute on function public.staff_update_offer(uuid,text,text,text,text,text,integer,date,text,numeric,jsonb) to authenticated;

create or replace function public.staff_send_offer(p_id uuid) returns public.teklifler language plpgsql security definer set search_path='' as $$ declare r public.teklifler; begin if not public.staff_can_any(array['offers.send','offers.manage']) then raise exception 'Teklif gönderme yetkiniz yok'; end if; update public.teklifler set status='sent',updated_at=now() where id=p_id returning * into r; if not found then raise exception 'Teklif bulunamadı'; end if; return r; end; $$;
revoke all on function public.staff_send_offer(uuid) from public;
grant execute on function public.staff_send_offer(uuid) to authenticated;
