import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const ALLOWED=new Set(["https://stagepulse.com.tr","https://www.stagepulse.com.tr"]);
const url=Deno.env.get("SUPABASE_URL")!; const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(url,service,{auth:{persistSession:false}});
const cors=(req:Request)=>{const o=req.headers.get("origin")||"";return {"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":ALLOWED.has(o)?o:"https://stagepulse.com.tr","Vary":"Origin","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Cache-Control":"no-store"}};
const out=(req:Request,b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors(req)});
async function auth(req:Request){const h=req.headers.get("authorization")||"";if(!/^bearer\s+/i.test(h))throw Object.assign(new Error("Oturum gerekli."),{status:401});const {data,error}=await db.auth.getUser(h.replace(/^bearer\s+/i,""));if(error||!data.user)throw Object.assign(new Error("Oturum geçersiz."),{status:401});const {data:m,error:me}=await db.from("org_memberships").select("active,role:role_id(code,name,tier,is_admin_role)").eq("user_id",data.user.id).eq("active",true).maybeSingle();if(me)throw Object.assign(new Error("Yetki doğrulaması başarısız."),{status:503});const r=Array.isArray((m as any)?.role)?(m as any).role?.[0]:(m as any)?.role;if(!m||r?.is_admin_role!==true)throw Object.assign(new Error("Yönetici yetkisi gerekli."),{status:403});return {id:data.user.id,role:r?.code||"admin"};}
async function context(){const [{count:offers},{count:jobs},{count:customers},{count:equipment},{count:unread}]=await Promise.all([db.from("teklifler").select("id",{count:"exact",head:true}),db.from("jobs").select("id",{count:"exact",head:true}),db.from("customers").select("id",{count:"exact",head:true}),db.from("equipment").select("id",{count:"exact",head:true}).eq("active",true),db.from("notifications").select("id",{count:"exact",head:true}).is("read_at",null)]);return {offers:offers||0,jobs:jobs||0,customers:customers||0,equipment:equipment||0,unread_notifications:unread||0};}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return out(req,{error:"Method Not Allowed"},405);try{const a=await auth(req);const b=await req.json().catch(()=>({}));const message=String(b.message||"").trim().slice(0,4000);if(!message)return out(req,{error:"Bir soru yazın."},400);const ctx=await context();const key=Deno.env.get("XAI_API_KEY")||Deno.env.get("OPENAI_API_KEY");if(!key)throw Object.assign(new Error("AI sağlayıcısı yapılandırılmamış."),{status:503});const base=Deno.env.get("XAI_API_KEY")?"https://api.x.ai/v1":"https://api.openai.com/v1";const model=Deno.env.get("AI_MODEL")||(Deno.env.get("XAI_API_KEY")?"grok-2-latest":"gpt-4o-mini");const system=`Sen Stagepulse yönetim yapay zekasısın. Kullanıcı yönetici/Patron hesabında. Türkçe, kısa ve uygulanabilir cevap ver. Gerçek veriyi değiştirme; yalnızca analiz, öneri ve plan üret. Finans, personel, teklif, operasyon ve güvenlik konularında uydurma veri üretme. Mevcut özet: ${JSON.stringify(ctx)}.`;const r=await fetch(`${base}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,messages:[{role:"system",content:system},{role:"user",content:message}],temperature:.2,max_tokens:700})});if(!r.ok)throw Object.assign(new Error(`AI sağlayıcısı ${r.status}`),{status:502});const j=await r.json();const reply=j?.choices?.[0]?.message?.content||"Yanıt üretilemedi.";await db.from("activity_logs").insert({actor_id:a.id,action:"admin_ai_query",entity_type:"ai",metadata:{role:a.role,message:message.slice(0,500)}}).then(()=>{}).catch(()=>{});return out(req,{reply,role:a.role,context:ctx});}catch(e){const s=typeof e==="object"&&e&&"status" in e&&typeof (e as any).status==="number"?(e as any).status:400;return out(req,{error:e instanceof Error?e.message:"AI işlemi başarısız."},s)}});
